const digimons = (() => {
  let db = [];
  for (let i = 0; i < MINI_DB.length; i++) {
    db.push({
      name: MINI_DB[i][0],
      img: MINI_DB[i][1],
      lv: MINI_DB[i][2],
      type: MINI_DB[i][3],
      form: MINI_DB[i][4],
      attribute: MINI_DB[i][5],
      evol: MINI_DB[i][6],
      authors: {
        madeBy: MINI_DB[i][7][0],
        editBy: MINI_DB[i][7][1],
        recolor: MINI_DB[i][7][2],
        redesign: MINI_DB[i][7][3],
        from: MINI_DB[i][7][4]
      },
      hidden: MINI_DB[i][8]
    });
  }
  return db.sort((previous, index) => (previous.img > index.img) ? 1 : -1);
})();

const attributes = {
  1: "Vaccine",
  2: "Virus",
  3: "Data",
  4: "Free",
  5: "Unknown",
  6: "Variable"
}

const forms = {
  1: "Fresh",
  2: "In-Training",
  3: "Rookie",
  4: "Champion",
  5: "Ultimate",
  6: "Mega",
  7: "Ultra",
  8: "Hybrid",
  9: "Armor"
}

const digimental = {
  allomon: 'courage',
  archelomon: 'reliability',
  aurumon: 'love',
  baromon: 'courage',
  boarmon: 'courage',
  bucchiemon: 'kindness',
  bucchiemon_green: 'kindness',
  bullmon: 'hope',
  butterflymon: 'knowledge',
  chamelemon: 'kindness',
  depthmon: 'reliability',
  digmon: 'knowledge',
  elephantmon: 'miracles',
  flamedramon: 'courage',
  flamewizardmon: 'courage',
  flybeemon: 'knowledge',
  frogmon: 'sincerity',
  gargoylemon: 'light',
  goldveedramon: 'destiny',
  halsemon: 'love',
  harpymon: 'light',
  honeybeemon: 'knowledge',
  kabukimon: 'sincerity',
  kangarumon: 'kindness',
  kenkimon: 'friendship',
  kongoumon: 'miracles|destiny',
  lynxmon: 'courage',
  magnamon: 'miracles',
  maildramon: 'miracles|destiny',
  manbomon: 'light',
  mantaraymon: 'reliability',
  moosemon: 'hope',
  mothmon: 'knowledge',
  nefertimon: 'light',
  nohemon: 'sincerity',
  opossummon: 'kindness',
  orcamon: 'reliability',
  oryxmon: 'hope',
  peacockmon: 'miracles',
  pegasusmon: 'hope',
  pilevolcamon: 'friendship',
  pipismon: 'love',
  ponchomon: 'sincerity',
  prairiemon: 'kindness',
  pteramon: 'love',
  quetzalmon: 'light',
  rabbitmon: 'friendship',
  raidramon: 'friendship',
  rapidmon_gold: 'destiny',
  rhinomon: 'miracles|destiny',
  rinkmon: 'friendship',
  sagittarimon: 'hope',
  salamandermon: 'courage',
  seahomon: 'light',
  searchmon: 'knowledge',
  sepikmon: 'friendship',
  sethmon: 'love',
  shadramon: 'courage',
  sheepmon: 'hope',
  shurimon: 'sincerity',
  stegomon: 'friendship',
  submarimon: 'reliability',
  swanmon: 'love',
  thunderbirdmon: 'friendship',
  togemogumon: 'friendship',
  toucanmon: 'kindness',
  tylomon: 'reliability',
  yasyamon: 'sincerity'
}

const types = (() => {
  let options = {
    Abnormal: "Abnormal",
    Amphibian: "Amphibian",
    Ancient: "Ancient",
    AncientAnimal: "Ancient Animal",
    AncientAnimalTenWarriors: "Ancient Animal/Ten Warriors",
    AncientBird: "Ancient Bird",
    AncientDragon: "Ancient Dragon",
    AncientDragonTenWarriors: "Ancient Dragon/Ten Warriors",
    AncientFish: "Ancient Fish",
    Angel: "Angel",
    Ankylosaur: "Ankylosaur",
    Aquabeast: "Aquabeast",
    Archangel: "Archangel",
    Armor: "Armor",
    ArmorLegendArms: "Armor/Legend-Arms",
    Authority: "Authority",
    Avian: "Avian",
    BabyDragon: "Baby Dragon",
    Beast: "Beast",
    Beastkin: "Beastkin",
    BeastkinBoss: "Beastkin/Boss",
    BeastKnight: "Beast Knight",
    Bird: "Bird",
    BirdDragon: "Bird Dragon",
    Birdkin: "Birdkin",
    Bulb: "Bulb",
    CarnivorousPlant: "Carnivorous Plant",
    Ceratopsian: "Ceratopsian",
    CherubThreeGreatAngels: "Cherub/Three Great Angels",
    Composite: "Composite",
    CRT: "CRT",
    Crustacean: "Crustacean",
    Cyborg: "Cyborg",
    CyborgDBrigade: "Cyborg/D-Brigade",
    DarkAnimal: "Dark Animal",
    DarkDragon: "Dark Dragon",
    DarkKnight: "Dark Knight",
    Demon: "Demon",
    DemonLord: "Demon Lord",
    DemonLordSevenGreatDemonLords: "Demon Lord/Seven Great Demon Lords",
    Dinosaur: "Dinosaur",
    Dragon: "Dragon",
    Dragonkin: "Dragonkin",
    DragonkinBigDeathStars: "Dragonkin/Big Death-Stars",
    EarthDragon: "Earth Dragon",
    Evil: "Evil",
    EvilDragon: "Evil Dragon",
    EvilDragonFourGreatDragons: "Evil Dragon/Four Great Dragons",
    Fairy: "Fairy",
    FairyBoss: "Fairy/Boss",
    FallenAngel: "Fallen Angel",
    FireDragon: "Fire Dragon",
    Flame: "Flame",
    Ghost: "Ghost",
    GiantBird: "Giant Bird",
    HolyBeast: "Holy Beast",
    HolyBeastDeva: "Holy Beast/Deva",
    HolyBird: "Holy Bird",
    HolyDragon: "Holy Dragon",
    HolyDragonFourGreatDragons: "Holy Dragon/Four Great Dragons",
    HolySwordLegendArms: "Holy Sword/Legend-Arms",
    HolyWarrior: "Holy Warrior",
    HolyWarriorRoyalKnight: "Holy Warrior/Royal Knight",
    HolyWarriorRoyalKnightXAntibody: "Holy Warrior/Royal Knight/X-Antibody",
    IceSnow: "Ice-Snow",
    Insectoid: "Insectoid",
    InsectoidBoss: "Insectoid/Boss",
    Larva: "Larva",
    Lesser: "Lesser",
    LightDragon: "Light Dragon",
    Machine: "Machine",
    MachineDBrigade: "Machine/D-Brigade",
    MachineDragon: "Machine Dragon",
    MagicKnight: "Magic Knight",
    MagicWarrior: "Magic Warrior",
    Major: "Major",
    Mammal: "Mammal",
    Mine: "Mine",
    Mineral: "Mineral",
    MineralBoss: "Mineral/Boss",
    MiniAngel: "Mini Angel",
    MiniBird: "Mini Bird",
    MiniDragon: "Mini Dragon",
    Minor: "Minor",
    Mollusk: "Mollusk",
    Mutant: "Mutant",
    MysteriousBeast: "Mysterious Beast",
    MysteriousBird: "Mysterious Bird",
    MythicalBeast: "Mythical Beast",
    MythicalDragon: "Mythical Dragon",
    Perfect: "Perfect",
    Plesiosaur: "Plesiosaur",
    Puppet: "Puppet",
    Reptile: "Reptile",
    Rock: "Rock",
    RockDragon: "Rock Dragon",
    SeaAnimal: "Sea Animal",
    SeaBeast: "Sea Beast",
    Seed: "Seed",
    SeraphThreeGreatAngels: "Seraph/Three Great Angels",
    Shaman: "Shaman",
    ShamanOlymposXII: "Shaman/Olympos XII",
    Slime: "Slime",
    Smoke: "Smoke",
    Spirit: "Spirit",
    SuperMajor: "Super Major",
    Throne: "Throne",
    ThroneThreeGreatAngels: "Throne/Three Great Angels",
    Undead: "Undead",
    Unidentified: "Unidentified",
    Unique: "Unique",
    UniqueLegendArms: "Unique/Legend-Arms",
    Vegetation: "Vegetation",
    Virtue: "Virtue",
    Warrior: "Warrior",
    Weapon: "Weapon",
    WeaponLegendArms: "Weapon/Legend-Arms",
    Wizard: "Wizard",
    Sovereigns: "Sovereigns"
  }
  let db = [];
  for (let op in options) {
    subOptions = options[op].split('/');
    if (subOptions.length == 1) {
      db.push(subOptions[0])
    } else {
      for (let subOp of subOptions) {
        if (!db.includes(subOp)) db.push(subOp);
      }
    }
  }
  return db.sort((previous, index) => (previous > index) ? 1 : -1);
})();

const authors = {
  1: 'Zebub',
  2: 'Dragonrod342',
  3: 'SergioGranSol',
  4: 'Lucho9',
  5: 'Opdisk',
  6: 'CadejoWhite',
  7: 'Topaz66',
  8: 'Arcanin1412',
  9: 'Neroesaurus',
  10: 'Demo9ic',
  11: 'BowchersDrawners',
  12: 'Matykiller',
  13: 'Sharkmon',
  14: 'WolfryHedgies',
  15: 'Maxtyrannus',
  16: 'Digimon games',
  17: 'Detcher',
  18: 'ScorchedDragonStudio'
}

const description = {
  redesign: (name, name2) =>
    `Sprite made by <span class="fst-italic text-dark">${name}</span> based on <span class="fst-italic text-dark">${name2}</span> art`,
  made: name => `Sprite made by <span class="fst-italic text-dark">${name}</span>`,
  edit: name => `Edit by <span class="fst-italic text-dark">${name}</span>`,
  recolor: name => `This sprite is recolored`
}