const MINI_DB_TYPES = [
  "Abnormal",
  "Alien",
  "Amphibian",
  "Ancient",
  "Ancient Animal",
  "Ancient Animal/Ten Warriors",
  "Ancient Beast/Ten Warriors",
  "Ancient Beast/X-Antibody",
  "Ancient Bird",
  "Ancient Birdkin/Ten Warriors",
  "Ancient Dragon",
  "Ancient Dragon/Ten Warriors",
  "Ancient Dragonkin",
  "Ancient Fish",
  "Ancient Insectoid/Ten Warriors",
  "Ancient Mineral/Ten Warriors",
  "Ancient Mutant/Ten Warriors",
  "Ancient Mythical Beast/Ten Warriors",
  "Ancient Plant/Ten Warriors",
  "Ancient Sea Beast/Ten Warriors",
  "Angel",
  "Ankylosaur",
  "Aquabeast",
  "Archangel",
  "Armor",
  "Armor/Legend-Arms",
  "Authority",
  "Avian",
  "Baby Dragon",
  "Battle Park/Holy Warrior",
  "Battle Park/Holy Warrior/X-Antibody",
  "Beast",
  "Beast Knight",
  "Beastkin",
  "Beastkin/Boss",
  "Bewitching Beast",
  "Bird",
  "Bird Dragon",
  "Birdkin",
  "Bulb",
  "Carnivorous Plant",
  "Ceratopsian",
  "Cherub",
  "Cherub/Three Great Angels",
  "Composite",
  "CRT",
  "Crustacean",
  "Cyborg",
  "Cyborg/Chaos General",
  "Cyborg/D-Brigade",
  "Cyborg/X-Antibody",
  "Dark Animal",
  "Dark Dragon",
  "Dark Knight",
  "Dark Knight/Core",
  "Demon",
  "Demon Lord",
  "Demon Lord/Larva",
  "Demon Lord/Seven Great Demon Lords",
  "Dinosaur",
  "Dinosaur/X-Antibody",
  "Dragon",
  "Dragon Knight",
  "Dragon/X-Antibody",
  "Dragonkin",
  "Dragonkin/Big Death-Stars",
  "Dragonkin/Chaos General",
  "Earth Dragon",
  "Evil",
  "Evil Dragon",
  "Evil Dragon/Four Great Dragons",
  "Fairy",
  "Fairy/Boss",
  "Fallen Angel",
  "Fire Dragon",
  "Flame",
  "Food",
  "Galaxy",
  "Ghost",
  "Giant Bird",
  "Holy Beast",
  "Holy Beast/Deva",
  "Holy Beast/Sovereigns",
  "Holy Bird",
  "Holy Bird/Deva",
  "Holy Bird/Sovereigns",
  "Holy Dragon",
  "Holy Dragon/Deva",
  "Holy Dragon/Four Great Dragons",
  "Holy Dragon/Four Great Dragons/Sovereigns",
  "Holy Dragon/Royal Knight",
  "Holy Dragon/Sovereigns",
  "Holy Sword/Legend-Arms",
  "Holy Warrior",
  "Holy Warrior/Royal Knight",
  "Holy Warrior/Royal Knight/X-Antibody",
  "Holy Warrior/X-Antibody",
  "Ice-Snow",
  "Insectoid",
  "Insectoid/Boss",
  "Larva",
  "Lesser",
  "Light Dragon",
  "Machine",
  "Machine Dragon",
  "Machine/D-Brigade",
  "Magic Knight",
  "Magic Warrior",
  "Major",
  "Mammal",
  "Mine",
  "Mineral",
  "Mineral/Boss",
  "Mini Angel",
  "Mini Bird",
  "Mini Dragon",
  "Minor",
  "Mollusk",
  "Monk",
  "Mutant",
  "Mutant/Boss",
  "Mysterious Beast",
  "Mysterious Bird",
  "Mythical Beast",
  "Mythical Dragon",
  "Perfect",
  "Plesiosaur",
  "Puppet",
  "Puppet/X-Antibody",
  "Reptile",
  "Rock",
  "Rock Dragon",
  "Sea Animal",
  "Sea Animal/X-Antibody",
  "Sea Beast",
  "Sea Man",
  "Seed",
  "Seraph/Three Great Angels",
  "Shaman",
  "Shaman/Olympos XII",
  "Slime",
  "Small Tyranny",
  "Smoke",
  "Spirit",
  "Super Major",
  "Throne",
  "Throne/Core",
  "Throne/Three Great Angels",
  "Undead",
  "Undead/X-Antibody",
  "Unidentified",
  "Unique",
  "Unique/Legend-Arms",
  "Vegetation",
  "Virtue",
  "Warrior",
  "Weapon",
  "Weapon/Legend-Arms",
  "Wizard",
  "Wizard/Chaos General"
]

const MINI_DB = [
`Aegiomon|aegiomon|4|Shaman/Olympos XII|4|||1|aegiochusmon,aegiochusmon_green,aegiochusmon_blue,aegiochusmon_dark,aegiochusmon_holy|13|||||true`,
`AeroVeedramon|aeroveedramon|5|Holy Dragon|5|||1|ulforceveedramon|01|||||false`,
`Agumon|agumon|3|Reptile|3|||1|greymon, centarumon, meramon, agumon_bond_of_bravery|01|||||false`,
`Agumon|agumon_black|3|Reptile|3|||2|greymon_blue, darktyrannomon, tyrannomon|01|||||false`,
`Agumon|agumon_savers|3|Dinosaur|3|||1|geogreymon||||03|01|false`,
`Agumon|agumon_savers_black|3|Dinosaur|3|||2|||||03|01|false`,
`Agumon|agumon_blue|3|Reptile|3|||1||01||03|||false`,
`Agumon|agumon_extra|3|Reptile|3|||1||01||03|||false`,
`Agumon|agumon_extra_green|3|Reptile|3|||1||01||03|||false`,
`Agumon|agumon_pink|3|Reptile|3|||1||01||03|||false`,
`Agumon|agumon_black_blue|3|Reptile|3|||2||01||03|||false`,
`Agumon Bond of Bravery|agumon_bond_of_bravery|7|Unidentified|7|||5||13|||||false`,
`Agumon Expert|agumon_expert|3|Dinosaur|3|||1|||||06|01|false`,
`Agunimon|agunimon|4|Wizard|8|||6|burninggreymon|16|||||false`,
`Agunimon|agunimon_blue|4|Wizard|8|||6||16||03|||false`,
`Agunimon|agunimon_extra|4|Wizard|8|||6||16||03|||false`,
`Agunimon|agunimon_extra_black|4|Wizard|8|||6||16||03|||false`,
`Airdramon|airdramon|4|Mysterious Beast|4|||1|metalgreymon_blue,kimeramon|01|||||false`,
`Airdramon|airdramon_gold|4|Mysterious Beast|4|||1||01||03|||false`,
`Akatorimon|akatorimon|4|Giant Bird|4|||3|sinduramon|01|||||false`,
`Aldamon|aldamon|5|Wizard|8||TRUE|6|emperorgreymon|07|||||false`,
`Allomon|allomon|4|Dinosaur|9|Courage||4||01|||||false`,
`Alphamon|alphamon|6|Holy Warrior/Royal Knight/X-Antibody|6|||1|alphamon_ouryuken|20|03||||false`,
`Alphamon|alphamon_white|6|Holy Warrior/X-Antibody|6|||1||20|03||||false`,
`Alphamon Ouryuken|alphamon_ouryuken|7|Holy Warrior/Royal Knight/X-Antibody|7||TRUE|1||20|03||||false`,
`AncientBeetlemon|ancientbeetlemon|6|Ancient Insectoid/Ten Warriors|6|||1||16|||||false`,
`AncientGarurumon|ancientgarurumon|6|Ancient Animal/Ten Warriors|6|||3||16|||||false`,
`AncientGreymon|ancientgreymon|6|Ancient Dragon/Ten Warriors|6|||1||16|||||false`,
`AncientKazemon|ancientkazemon|6|Ancient Birdkin/Ten Warriors|6|||1||16|||||false`,
`AncientMegatheriummon|ancientmegatheriummon|6|Ancient Beast/Ten Warriors|6|||3||16|||||false`,
`AncientMermaimon|ancientmermaimon|6|Ancient Sea Beast/Ten Warriors|6|||3||07|||||false`,
`AncientSphinxmon|ancientsphinxmon|6|Ancient Mythical Beast/Ten Warriors|6|||2||07|||||false`,
`AncientTroiamon|ancienttroiamon|6|Ancient Plant/Ten Warriors|6|||6||07|||||false`,
`AncientVolcanomon|ancientvolcanomon|6|Ancient Mineral/Ten Warriors|6|||6||07|||||false`,
`AncientWisemon|ancientwisemon|6|Ancient Mutant/Ten Warriors|6|||2||07|||||false`,
`Andromon|andromon|5|Cyborg|5|||1|hiandromon,machinedramon|01|||||false`,
`Angemon|angemon|4|Angel|4|||1|magnaangemon, shakkoumon, angewomon, devimon,kimeramon|01|||||false`,
`Angewomon|angewomon|5|Archangel|5|||1|magnadramon, ophanimon, mastemon, ophanimon_falldown_mode, lovelyangemon|01|||||false`,
`Ankylomon|ankylomon|4|Ankylosaur|4|||4|shakkoumon,seahomon|01|||||false`,
`Antylamon|antylamon|5|Holy Beast|5|||2|cherubimon,cherubimon_virus|01|||||false`,
`Antylamon|antylamon_deva|5|Holy Beast/Deva|5|||3|cherubimon,cherubimon_virus|01|||||false`,
`Antylamon|antylamon_white|5|Holy Beast|5|||2||01||03|||false`,
`Apemon|apemon|4|Beastkin|4|||1|mammothmon,gokuwmon|01|||||false`,
`Apocalypmon|apocalypmon|7|Unidentified|7|||5||10|||||false`,
`Apollomon|apollomon|6|Shaman/Olympos XII|6|||1|gracenovamon||||02|10|false`,
`Aquilamon|aquilamon|4|Giant Bird|4|||4|silphymon, angewomon, garudamon,shurimon|05|02|03|||false`,
`Arbormon|arbormon|4|Cyborg|8|||6|petaldramon|07|||02|16|false`,
`Arcadiamon|arcadiamon_intraining|2|Lesser|2|||4|arcadiamon_rookie|13|||||false`,
`Arcadiamon|arcadiamon_rookie|3|Bewitching Beast|3|||2|arcadiamon_champion||||02|18|false`,
`Archelomon|archelomon|4|Reptile|9|Sincerity||3||18|||||false`,
`Argomon|argomon_fresh|1|Mutant|1|||4|argomon_intraining|03|||||false`,
`Argomon|argomon_intraining|2|Mutant|2|||4|argomon_rookie|03|||||false`,
`Argomon|argomon_rookie|3|Mutant|3|||2|argomon_champion|02|||||false`,
`Armadillomon|armadillomon|3|Mammal|3|||4|ankylomon,chamelemon,shakkoumon,sepikmon,boarmon,kenkimon,pteramon,frogmon,digmon,submarimon,sheepmon,seahomon,chamelemon,elephantmon|01|||||false`,
`Armageddemon|armageddemon|7|Unidentified|7|||5||16|||||false`,
`Armormon|armormon|5|Cyborg|5|||2||01|||||false`,
`Arukenimon|arukenimon|5|Dark Animal|5|||2||01|||||false`,
`Aruraumon|aruraumon|3|Vegetation|3|||3||01|||||false`,
`Astamon|astamon|5|Demon Lord|5|||2|belphemon_sleep_mode|10|02|03|||false`,
`Asuramon|asuramon|5|Wizard|5|||1|zanbamon|01|||||false`,
`AtlurBallistamon|atlurballistamon|5|Machine|5|||1||02|||||true`,
`Azulongmon|azulongmon|6|Holy Dragon/Four Great Dragons/Sovereigns|6|||3|huanglongmon|02|||||false`,
`Babamon|babamon|6|Ancient|6|||1||01|||||false`,
`Baboongamon|baboongamon|4|Beast|4|||1||13|||||false`,
`Babydmon|babydmon|2|Baby Dragon|2|||4|dracomon|02|03||||false`,
`Baihumon|baihumon|6|Holy Beast/Sovereigns|6|||3|huanglongmon|02|||||false`,
`Bakemon|bakemon|4|Ghost|4|||2|phantomon,myotismon,bluemeramon,pumpkinmon|01|||||false`,
`Ballistamon|ballistamon|4|Machine|4|||1||02|||||true`,
`BanchoGolemon|banchogolemon|6|Mineral/Boss|6|||2||09|||||false`,
`BanchoLeomon|bancholeomon|6|Beastkin/Boss|6|||1|chaosmon,chaosmon_valdur_arm,marsmon|13|03||||false`,
`BanchoLillymon|bancholillymon|6|Fairy/Boss|6|||3||10|||||false`,
`BanchoMamemon|banchomamemon|6|Mutant/Boss|6|||3||09|||||false`,
`BanchoStingmon|banchostingmon|6|Insectoid/Boss|6|||4||10|||||false`,
`BaoHuckmon|baohuckmon|4|Dinosaur|4|||3|saviorhuckmon|02|||||false`,
`Barbamon|barbamon|6|Demon Lord/Seven Great Demon Lords|6|||2|ogudomon|02|||||false`,
`Barbamon|barbamon_black|6|Demon Lord/Seven Great Demon Lords|6|||2||02||03|||false`,
`Baromon|baromon|4|Wizard|9|Courage||4||01|||||false`,
`Bastemon|bastemon|5|Beastkin|5|||2|barbamon,laylamon|01|||||false`,
`Bearmon|bearmon|3|Beast|3|||1|grizzlymon,loaderliomon|01|||||false`,
`Beelzemon|beelzemon|6|Demon Lord/Seven Great Demon Lords|6|||2|beelzemon_blast_mode||||03|13|false`,
`Beelzemon|beelzemon_red|6|Demon Lord/Seven Great Demon Lords|6|||2||||03|03|13|false`,
`Beelzemon Blast Mode|beelzemon_blast_mode|6|Demon Lord/Seven Great Demon Lords|6|||2|||||03|02|false`,
`Beelzemon Blast Mode|beelzemon_blast_mode_gold|6|Demon Lord/Seven Great Demon Lords|6|||2||||03|03|02|false`,
`Beetlemon|beetlemon|4|Cyborg|8|||6|metalkabuterimon|16|||||false`,
`Beetlemon|beetlemon_red|4|Cyborg|8|||6||16||03|||false`,
`BelleStarmon|bellestarmon|6|Demon Lord|6|||2||02|||||true`,
`Belphemon Sleep Mode|belphemon_sleep_mode|6|Demon Lord/Seven Great Demon Lords|6|||2|belphemon_rage_mode|15|02||||false`,
`BeoWolfmon|beowolfmon|5|Warrior|8||TRUE|6|magnagarurumon|07|||||false`,
`Betamon|betamon|3|Amphibian|3|||2|seadramon|01|||||false`,
`Bibimon|bibimon|2|Lesser|2|||4|pulsemon||||03|21|false`,
`BigMamemon|bigmamemon|5|Mutant|5|||3|princemamemon|01|||||false`,
`Birdramon|birdramon|4|Giant Bird|4|||1|garudamon|01|||||false`,
`Biyomon|biyomon|3|Bird|3|||1|birdramon,aquilamon,kokatorimon|01|||||false`,
`BlackGaogamon|blackgaogamon|4|Beast|4|||3|blackmachgaogamon|02||03|||false`,
`BlackGargomon|blackgargomon|4|Beastkin|4|||2|blackrapidmon|01||03|||false`,
`BlackGatomon|blackgatomon|4|Dark Animal|4|||2|ladydevimon|01|||||false`,
`BlackGrowlmon|blackgrowlmon|4|Dark Dragon|4|||2|blackwargrowlmon|01|||||false`,
`BlackKingNumemon|blackkingnumemon|5|Mollusk|5|||2|platinumnumemon|01|||||false`,
`BlackMachGaogamon|blackmachgaogamon|5|Cyborg|5|||3|zeedgarurumon|02||03|||false`,
`BlackMegaGargomon|blackmegagargomon|6|Machine|6|||2||01|||||false`,
`BlackMegaGargomon|blackmegagargomon_purple|6|Machine|6|||2||01||03|||false`,
`BlackRapidmon|blackrapidmon|5|Cyborg|5|||2|blackmegagargomon|01||03|||false`,
`BlackSeraphimon|blackseraphimon|6|Seraph|6|||2||01||03|||false`,
`BlackWarGreymon|blackwargreymon|6|Dragonkin|6|||2|omnimon_zwart|01|||||false`,
`BlackWarGreymon|blackwargreymon_red|6|Dragonkin|6|||2||01||03|||false`,
`BlackWarGrowlmon|blackwargrowlmon|5|Cyborg|5|||2|chaosgallantmon|01|||||false`,
`BlitzGreymon|blitzgreymon|6|Cyborg|6|||2|omnimon_alter_s|16|03||||false`,
`BloomLordmon|bloomlordmon|6|Fairy|6|||1||13|||||false`,
`Blossomon|blossomon|5|Vegetation|5|||3|gryphonmon,lotosmon|01|||||false`,
`Blossomon|blossomon_pink|5|Vegetation|5|||3||01||03|||false`,
`Blossomon|blossomon_yellow|5|Vegetation|5|||3||01||03|||false`,
`BlueMeramon|bluemeramon|5|Flame|5|||3|skullmeramon,boltmon|01|||||false`,
`Boarmon|boarmon|4|Mammal|9|Courage||4|mammothmon|01|||||false`,
`Bokomon|bokomon|3|Mutant|3|||1||01|||||false`,
`Boltmon|boltmon|6|Cyborg|6|||3||01|||||false`,
`BomberNanimon|bombernanimon|4||4|||2||01|||||false`,
`Bombmon|bombmon|1|Slime|1|||4||03|||||false`,
`Bombmon|bombmon_super|1|Slime|1|||4||03|||||false`,
`Bommon|bommon|1|Slime|1|||4|missimon|03|||||false`,
`Boogiemon|boogiemon|4|Demon|4|||2||01|||||false`,
`Botamon|botamon|1|Slime|1|||4|koromon,wanyamon|01|||||false`,
`Brachiomon|brachiomon|5|Dinosaur|5|||3||02|||||false`,
`Brachiomon|brachiomon_grey|5|Dinosaur|5|||3||02||03|||false`,
`Breakdramon|breakdramon|6|Machine Dragon|6|||2|examon|20||03|||false`,
`Bucchiemon|bucchiemon|4|Fairy|9|Kindness||1|||||03|07|false`,
`Bucchiemon|bucchiemon_green|4|Fairy|9|Kindness||4|||||03|07|false`,
`Budmon|budmon|2|Vegetation|2|||4|lalamon|06|03||||false`,
`Bukamon|bukamon|2|Lesser|2|||4|gomamon,betamon|01|||||false`,
`Bullmon|bullmon|4|Mammal|9|Hope||4||08|||||false`,
`Bulucomon|bulucomon|3|Mini Dragon|3|||3|paledramon|02|||||false`,
`Burgermon|burgermon|3|Food|3|||1|burgermon_champion|01|||||false`,
`BurningGreymon|burninggreymon|4|Dark Dragon|8|||6|aldamon|16|||||false`,
`BurningGreymon|burninggreymon_purple|4|Dark Dragon|8|||6||16||03|||false`,
`BushiAgumon|bushiagumon|3|Dinosaur|3|||1|||||03|01|false`,
`Butterflymon|butterflymon|4|Insectoid|9|Knowledge||1||08|||||false`,
`Calmaramon|calmaramon|4|Aquabeast|8|||6||07|||||false`,
`Calumon|calumon|2|Unidentified|2|||1|||||03|02|false`,
`Candlemon|candlemon|3|Flame|3|||3|wizardmon,meramon,reverse_weddinmon,starmon|01|||||false`,
`CannonBeemon|cannonbeemon|5|Cyborg|5|||2|tigervespamon|08|||||false`,
`Cannondramon|cannondramon|6|Cyborg|6|||3||02|||||false`,
`CaptainHookmon|captainhookmon|5|Sea Man|5|||1||13|||||false`,
`Caturamon|caturamon|5|Holy Beast/Deva|5|||3|||||||true`,
`Centarumon|centarumon|4|Beastkin|4|||3|sagittarimon|01|||||false`,
`Cerberusmon|cerberusmon|5|Dark Animal|5|||1|anubismon,ancientsphinxmon,cerberusmon_werewolf_mode|01|||||false`,
`Cerberusmon Werewolf Mode|cerberusmon_werewolf_mode|5|Wizard|5|||1|plutomon|11|||||false`,
`Ceresmon|ceresmon|6|Shaman/Olympos XII|6|||3|ceresmon_medium|13|||||false`,
`Ceresmon Medium|ceresmon_medium|6|Shaman/Olympos XII|6|||3||02|||||true`,
`Chamelemon|chamelemon|4|Reptile|9|Kindness||2||02|||||false`,
`ChaosBlackWarGreymon|chaosblackwargreymon|6|Dragonkin/Chaos General|6|||2||01|03||||false`,
`Chaosdramon|chaosdramon|6|Machine|6|||2|||||03|01|false`,
`ChaosGallantmon|chaosgallantmon|6|Dark Knight|6|||2|gallantmon_chaos_mode,chaosgallantmon_core|01||03|||false`,
`ChaosGallantmon Core|chaosgallantmon_core|6|Dark Knight/Core|6|||2||01||03|||false`,
`ChaosMetalSeadramon|chaosmetalseadramon|6|Cyborg/Chaos General|6|||3|gigaseadramon|01|||||false`,
`Chaosmon|chaosmon|7|Unique|7||TRUE|1||02|||||false`,
`Chaosmon Valdur Arm|chaosmon_valdur_arm|7|Unique|7||TRUE|1||02|||||false`,
`ChaosPiedmon|chaospiedmon|6|Wizard/Chaos General|6|||2||01|||||false`,
`Chapmon|chapmon|2|Lesser|2|||4||21||03|||false`,
`Cherrymon|cherrymon|5|Vegetation|5|||2|puppetmon,ghoulmon|01|||||false`,
`Cherrymon|cherrymon_brown|5|Vegetation|5|||2||01||03|||false`,
`Cherubimon|cherubimon|6|Cherub/Three Great Angels|6|||1||01|||||false`,
`Cherubimon|cherubimon_virus|6|Cherub|6|||2||01|||||false`,
`Chibickmon|chibickmon|1|Slime|1|||4|pickmon,pickmon_yellow,pickmon_red,pickmon_super|02|||||false`,
`Chibomon|chibomon|1|Slime|1|||4|demiveemon|01|||||false`,
`Chicchimon|chicchimon|2|Mini Bird|2|||1|hyokomon,penguinmon,muchomon,falcomon_savers||||03|01|false`,
`Chirinmon|chirinmon|5|Holy Beast|5|||1|kentaurosmon,mitamamon|02|||||false`,
`Chuumon|chuumon|3|Beast|3|||2|tyrannomon,salamandermon,seahomon|01|||||false`,
`Chuumon|chuumon_yellow|3|Beast|3|||2||01||03|||false`,
`Citramon|citramon|4|Food|4|||2||01|03||||false`,
`ClavisAngemon|clavisangemon|6|Virtue|6|||1||08|||||false`,
`ClearToyAgumon|cleartoyagumon|3|Puppet|3|||1|elephantmon,peacockmon,maildramon|01|||||false`,
`Clockmon|clockmon|4|Machine|4|||3||01|||||false`,
`Coelamon|coelamon|4|Ancient Fish|4|||3||01|||||false`,
`Commandramon|commandramon|3|Cyborg/D-Brigade|3|||2|sealsdramon|01||03|||false`,
`Conomon|conomon|1|Slime|1|||4|kokomon|01|||||false`,
`Coredramon|coredramon|4|Dragon|4|||2|groundramon|03|||||false`,
`Coredramon|coredramon_blue|4|Dragon|4|||1|wingdramon|03|||||false`,
`Cotsucomon|cotsucomon|1|Armor|1|||4|kakkinmon|02|||||false`,
`Crabmon|crabmon|3|Crustacean|3|||3|coelamon|01|||||false`,
`Crabmon|crabmon_red|3|Crustacean|3|||3||01||03|||false`,
`Crabmon|crabmon_white|3|Crustacean|3|||3||01||03|||false`,
`Craniamon|craniamon|6|Holy Warrior/Royal Knight|6|||1||12|||||false`,
`CresGarurumon|cresgarurumon|6|Beast Knight|6|||3|omnimon_alter_s|03|02||||false`,
`Crowmon|crowmon|5|Mysterious Bird|5|||1|ravemon|02|03||||false`,
`CrysPaledramon|cryspaledramon|5|Dragonkin|5|||3|hexeblaumon|02|||||false`,
`Cutemon|cutemon|3|Fairy|3|||3||02|03||||false`,
`Cyberdramon|cyberdramon|5|Cyborg|5|||1|justimon|01|||||false`,
`Cyclonemon|cyclonemon|4|Dragon|4|||2||01|||||false`,
`Cyclonemon|cyclonemon_red|4|Dragon|4|||2||01||03|||false`,
`Daemon|daemon|6|Demon Lord|6|||2|ogudomon|01|||||false`,
`Daemon|daemon_black|6|Demon Lord|6|||2||01||03|||false`,
`Daemon (Mantled)|daemon_mantled|6|Evil|6|||2|daemon|01|||||false`,
`Daemon (Mantled)|daemon_mantled_red|6|Evil|6|||2||01||03|||false`,
`Daipenmon|daipenmon|5|Cyborg|8||TRUE|6||13|||||false`,
`Darkdramon|darkdramon|6|Cyborg/D-Brigade|6|||2|chaosmon|10|03||||false`,
`DarkLizardmon|darklizardmon|4|Fire Dragon|4|||2|metaltyrannomon|01|||||false`,
`DarkSuperStarmon|darksuperstarmon|5|Mutant|5|||2||01||03|||false`,
`DarkTyrannomon|darktyrannomon|4|Dinosaur|4|||2|metaltyrannomon,antylamon|01|||||false`,
`Datamon|datamon|5|Machine|5|||2||01|||||false`,
`Datirimon|datirimon|1|Slime|1|||4||01|||||false`,
`Deltamon|deltamon|4|Composite|4|||2|kimeramon|01|||||false`,
`DemiDevimon|demidevimon|3|Evil|3|||2|devimon,bakemon,soulmon|01|||||false`,
`DemiDevimon|demidevimon_purple|3|Evil|3|||2||01||03|||false`,
`DemiVeemon|demiveemon_green|2|Baby Dragon|2|||4||01||03|||false`,
`DemiMeramon|demimeramon|2|Flame|2|||4|candlemon,vorvomon|01|||||false`,
`DemiVeemon|demiveemon|2|Baby Dragon|2|||4|veemon|01|||||false`,
`Depthmon|depthmon|4|Sea Animal|9|Sincerity||4||03|||||false`,
`Deputymon|deputymon|4|Mutant|4|||1|superstarmon|01|||||false`,
`Deputymon|deputymon_purple|4|Mutant|4|||1||01||03|||false`,
`Deramon|deramon|5|Avian|5|||3||01|||||false`,
`Devidramon|devidramon|4|Evil Dragon|4|||2|cyberdramon,mephistomon|01|||||false`,
`Devimon|devimon|4|Fallen Angel|4|||2|neodevimon,myotismon,skullsatamon,kimeramon,bluemeramon|01|||||false`,
`DexDorugamon|dexdorugamon|4|Undead|4|||3|dexdorugreymon,samudramon,hisyaryumon|02|||||false`,
`DexDoruGreymon|dexdorugreymon|5|Undead|5|||2|dexdorugoramon||||02|15|false`,
`Diaboromon|diaboromon|6|Unidentified|6|||5|armageddemon|01||03|||false`,
`Digitamamon|digitamamon|5|Perfect|5|||3|devitamamon,minervamon,titamon|01|||||false`,
`Digmon|digmon|4|Insectoid|9|Knowledge||4||01|||||false`,
`Dinobeemon|dinobeemon|5|Mutant|5||TRUE|4|grankuwagamon,imperialdramon_dragon_mode,tigervespamon|01|||||false`,
`Dinorexmon|dinorexmon|6|Dinosaur/X-Antibody|6|||3||13|||||false`,
`Dinotigermon|dinotigermon|6|Ancient Beast/X-Antibody|6|||3|bancholeomon|13|||||false`,
`Divermon|divermon|5|Sea Animal|5|||3||01|||||false`,
`Dobermon|dobermon|4|Dark Animal|4|||1|cerberusmon|01|||||false`,
`Dodomon|dodomon|1|Slime|1|||4|dorimon,wanyamon|01|||||false`,
`Doggymon|doggymon|4|Puppet|4|||3|cerberusmon|01|||||false`,
`Dokimon|dokimon|1|Slime|1|||4|bibimon|03|||||false`,
`Dokugumon|dokugumon|4|Insectoid|4|||2|arukenimon|01|||||false`,
`Dokugumon|dokugumon_red|4|Insectoid|4|||2||01||03|||false`,
`DoKunemon|dokunemon|3|Larva|3|||2|dokugumon|01|||||false`,
`Dolphmon|dolphmon|4|Sea Animal|4|||1|whamon|01|||||false`,
`Dorbickmon|dorbickmon|6|Dragonkin|6|||2||02|||||false`,
`Dorimon|dorimon|2|Lesser|2|||4|dorumon|01|||||false`,
`Dorugamon|dorugamon|4|Dragon|4|||3|dorugreymon,dexdorugreymon|02|||||false`,
`DoruGreymon|dorugreymon|5|Dragon|5|||3|dorugoramon,alphamon,dexmon,samudramon||||02|01|false`,
`Dorumon|dorumon|3|Beast|3|||3|dorugamon,dexdorugamon,reptiledramon|01|||||false`,
`Doumon|doumon|5|Wizard|5|||3|kuzuhamon,kuzuhamon_maid_mode|01|||||false`,
`Dracomon|dracomon|3|Dragon|3|||3|coredramon,coredramon_blue|02|||||false`,
`Dragomon|dragomon|5|Sea Animal|5|||2||01|||||false`,
`Drimogemon|drimogemon|4|Beast|4|||3|giromon|01|||||false`,
`Drimogemon|drimogemon_red|4|Beast|4|||3||01||03|||false`,
`Duskmon|duskmon|4|Demon|8|||6|velgemon|07|||||false`,
`Dynasmon|dynasmon|6|Holy Warrior/Royal Knight|6|||3||01|||||false`,
`Eaglemon|eaglemon|6|Cyborg|6|||1||01|||||false`,
`Ebemon|ebemon|6|Cyborg|6|||2||01|||||false`,
`EbiBurgermon|ebiburgermon|3|Food|3|||3||01|||||false`,
`Ebidramon|ebidramon|4|Crustacean|4|||3||01|||||false`,
`Ebidramon|ebidramon_pink|4|Crustacean|4|||3||01||03|||false`,
`Ebonwumon|ebonwumon|6|Holy Beast/Sovereigns|6|||1|huanglongmon|02|||||false`,
`ElDradimon|eldradimon|6|Mutant|6|||3||02|||||true`,
`Elecmon|elecmon|3|Mammal|3|||3|garurumon_black,leomon|01|||||false`,
`Elecmon|elecmon_violet|3|Mammal|3|||2||01|||||false`,
`Elephantmon|elephantmon|4|Cyborg|9|Miracles||4||02|||||true`,
`EmperorGreymon|emperorgreymon|6|Dragon Knight|8||TRUE|6|susanoomon|02|||||false`,
`Eosmon|eosmon_champion|4|Unidentified|4|||5|eosmon_ultimate|13|||||false`,
`Eosmon|eosmon_mega|6|Unidentified|6|||5||13|||||false`,
`Eosmon|eosmon_ultimate|5|Unidentified|5|||5|eosmon_mega|13|||||false`,
`Etemon|etemon|5|Puppet|5|||2|metaletemon|01|||||false`,
`Examon|examon|7|Holy Dragon/Royal Knight|7||TRUE|3||02|||||false`,
`ExTyrannomon|extyrannomon|5|Puppet|5|||1||01|||||false`,
`ExVeemon|exveemon|4|Mythical Beast|4|||4|paildramon,dinobeemon,flamedramon,magnamon|01|||||false`,
`ExVeemon|exveemon_black|4|Mythical Beast|4|||2||01||03|||false`,
`Fake Agumon Expert|fake_agumon_expert|3|Dinosaur|3|||2|||||06|01|false`,
`Falcomon|falcomon|3|Avian|3|||1|diatrymon|05|||||false`,
`Falcomon|falcomon_savers|3|Avian|3|||1|peckmon|05||03|||false`,
`Firamon|firamon|4|Beast|4|||1|flaremon|02|||||false`,
`Flamedramon|flamedramon|4|Dragonkin|9|Courage||4||01|||||false`,
`Flamemon|flamemon|3|Wizard|8|||6|agunimon|03|||||false`,
`FlameWizardmon|flamewizardmon|4|Wizard|9|Courage||2||01|||||false`,
`Flaremon|flaremon|5|Beastkin|5|||1|apollomon|02|||||false`,
`Flarerizamon|flarerizamon|4|Fire Dragon|4|||3||01|||||false`,
`Floramon|floramon|3|Vegetation|3|||3|kiwimon,ninjamon,vegiemon|01|||||false`,
`Flybeemon|flybeemon|4|Insectoid|9|Knowledge||4||08|03||||false`,
`Flymon|flymon|4|Insectoid|4|||2|okuwamon|01|||||false`,
`Flymon|flymon_pink|4|Insectoid|4|||2||01||03|||false`,
`Flymon|flymon_striped|4|Insectoid|4|||2||01||03|||false`,
`Frigimon|frigimon|4|Ice-Snow|4|||1|pandamon|01|||||false`,
`Frimon|frimon|2|Lesser|2|||4||03|||||false`,
`FrosVelgrmon|frosvelgrmon|6|Giant Bird|6|||2||20|||||false`,
`Fufumon|fufumon|1|Slime|1|||4|kyokyomon|02|03||||false`,
`Fugamon|fugamon|4|Demon|4|||2||01|||||false`,
`Fujinmon|fujinmon|6|Cyborg|6|||1|||||02|05|true`,
`Gabumon|gabumon|3|Reptile|3|||3|garurumon,gabumon_bond_of_friendship,kenkimon|01||03|||false`,
`Gabumon|gabumon_black|3|Reptile|3|||2|garurumon_black,blackgaogamon,kenkimon,moosemon|01||03|||false`,
`Gabumon|gabumon_white|3|Reptile|3|||3||01||03|||false`,
`Gabumon|gabumon_pink|3|Reptile|3|||3||01||03|||false`,
`Gabumon|gabumon_orange|3|Reptile|3|||3||01||03|||false`,
`Gabumon Bond of Friendship|gabumon_bond_of_friendship|7|Unidentified|7|||5||13|||||false`,
`Gallantmon|gallantmon|6|Holy Warrior/Royal Knight|6|||2|gallantmon_crimson_mode|01|||||false`,
`Gallantmon|gallantmon_green|6|Holy Warrior|6|||2||01||03|||false`,
`Gallantmon|gallantmon_blue|6|Holy Warrior/Royal Knight|6|||2||01||03|||false`,
`Gallantmon Chaos Mode|gallantmon_chaos_mode|7|Holy Warrior|7|||2||01||03|||false`,
`Gallantmon Crimson Mode|gallantmon_crimson_mode|7|Holy Warrior|7|||1||01|||||false`,
`Ganemon|ganemon|4|Mutant|4|||1||02|||||true`,
`Gankoomon|gankoomon|6|Holy Warrior/Royal Knight|6|||3||11|||||false`,
`Gaogamon|gaogamon|4|Beast|4|||3|machgaogamon|02|||||false`,
`Gaomon|gaomon|3|Beast|3|||3|gaogamon,blackgaogamon||||03|02|false`,
`Gaossmon|gaossmon|3|Reptile|3|||2||02||03|||false`,
`Garbagemon|garbagemon|5|Mutant|5|||2||01|||||false`,
`Gargomon|gargomon|4|Beastkin|4|||1|rapidmon,antylamon,prairiemon|01||03|||false`,
`Gargoylemon|gargoylemon|4|Dark Animal|9|Light||4||01|||||false`,
`Garudamon|garudamon|5|Birdkin|5|||1|phoenixmon|01|||||false`,
`Garurumon|garurumon|4|Beast|4|||1|weregarurumon,weregarurumon_black,kimeramon|01|||||false`,
`Garurumon|garurumon_black|4|Beast|4|||2|weregarurumon_black,pandamon|01|||||false`,
`Gatomon|gatomon|4|Holy Beast|4|||1|angewomon,silphymon,lynxmon,rabbitmon,swanmon,kabukimon,butterflymon,tylomon,oryxmon,nefertimon,opossummon,maildramon|01|||||false`,
`Gatomon|gatomon_red_claws|4|Holy Beast|4|||1||01||03|||false`,
`Gatomon|gatomon_no_ring|4|Holy Beast|4|||1||01||03|||false`,
`Gatomon|gatomon_red|4|Holy Beast|4|||1||01||03|||false`,
`Gazimon|gazimon|3|Mammal|3|||2|devidramon,deltamon,garurumon_black,leomon|01|||||false`,
`Gekomon|gekomon|4|Amphibian|4|||2|shogungekomon,whamon|01|||||false`,
`GeoGreymon|geogreymon|4|Dinosaur|4|||1|rizegreymon||||02|01|false`,
`Geremon|geremon|4|Mollusk|4|||2||01|||||false`,
`Gesomon|gesomon|4|Mollusk|4|||2|marinedevimon|01|||||false`,
`Ghostmon|ghostmon|3|Ghost|3|||3||13|||||false`,
`Ghoulmon|ghoulmon|6|Demon Lord|6|||2||01|||||false`,
`Ghoulmon|ghoulmon_black|6|Demon Lord|6|||2||01|||||false`,
`GigaBreakdramon|gigabreakdramon|6|Machine Dragon|6|||2||20||03|||false`,
`Gigadramon|gigadramon|5|Cyborg|5|||2||01|||||false`,
`GigaSeadramon|gigaseadramon|6|Cyborg/X-Antibody|6|||3|apocalymon|13|||||false`,
`Gigasmon|gigasmon|4|Mineral|8|||6||07|||||false`,
`Gigimon|gigimon|2|Lesser|2|||4|guilmon|01|||||false`,
`Giromon|giromon|5|Mine|5|||1|hiandromon|01|||||false`,
`Gizamon|gizamon|3|Sea Animal|3|||2|datamon|01|||||false`,
`Gladimon|gladimon|4|Warrior|4|||1|knightmon|01|||||false`,
`Goblimon|goblimon|3|Demon|3|||2|fugamon,ogremon|01|||||false`,
`Goblimon|goblimon_red|3|Demon|3|||2||01||03|||false`,
`Gogmamon|gogmamon|5|Rock|5|||1||13|||||false`,
`GoldNumemon|goldnumemon|4|Mutant|4|||2||01|||||false`,
`Goldramon|goldramon|6|Holy Dragon/Four Great Dragons|6|||1||01|||||false`,
`GoldVeedramon|goldveedramon|4|Mythical Dragon|9|Fate||1||01|||||false`,
`Golemon|golemon|4|Mineral|4|||2|gogmamon|01|||||false`,
`Gomamon|gomamon|3|Sea Beast|3|||1|ikkakumon,gaogamon,mojyamon|01|||||false`,
`Gorillamon|gorillamon|4|Beastkin|4|||3||01|||||false`,
`Goromon|goromon|2|Mineral|2|||4||03|||||false`,
`Gotsumon|gotsumon|3|Rock|3|||3|monochromon,icemon,minotarumon,golemon,stegomon,thunderbirdmon|01|||||false`,
`GraceNovamon|gracenovamon|7|Galaxy|7||TRUE|1||13|||||false`,
`GranDracmon|grandracmon|6||6|||2|||||02|14|false`,
`GranKuwagamon|grankuwagamon|6|Insectoid|6|||4|grandiskuwagamon|01|||||false`,
`GrapLeomon|grapleomon|5|Beastkin|5|||1|saberleomon,bancholeomon,leopardmon,heavyleomon|01|||||false`,
`Greymon|greymon|4|Dinosaur|4|||1|metalgreymon,metalgreymon_blue,skullgreymon,kimeramon|01|||||false`,
`Greymon|greymon_blue|4|Dinosaur|4|||2|metalgreymon_blue|01||03|||false`,
`Greymon|greymon_xros|4|Dinosaur|4|||2|||||03|01|false`,
`Greymon|greymon_xros_orange|4|Dinosaur|4|||2|||||03|01|false`,
`Greymon|greymon_xros_ash|4|Dinosaur|4|||2|||||03|01|false`,
`Grizzlymon|grizzlymon|4|Beast|4|||1|monzaemon,pandamon,grapleomon|01|||||false`,
`Groundramon|groundramon|5|Earth Dragon|5|||2|breakdramon|20||03|||false`,
`Growlmon|growlmon|4|Dark Dragon|4|||2|wargrowlmon,skullgreymon|01|||||false`,
`Growlmon|growlmon_orange|4|Dark Dragon|4|||3|wargrowlmon_yellow|01|||||false`,
`Grumblemon|grumblemon|4||8|||6|gigasmon|07|||||false`,
`Gryphonmon|gryphonmon|6|Mythical Beast|6|||3||01|||||false`,
`Guardromon|guardromon|4|Machine|4|||2|andromon,kenkimon,guardromon_gold|01|||||false`,
`Guardromon|guardromon_gold|4|Machine|4|||2|andromon,magnamon,rapidmon_gold|01||03|||false`,
`Guardromon|guardromon_silver|4|Machine|4|||2||01||03|||false`,
`Guardromon|guardromon_blue|4|Machine|4|||2||01||03|||false`,
`Guardromon|guardromon_bronze|4|Machine|4|||2||01||03|||false`,
`Guilmon|guilmon|3|Reptile|3|||2|growlmon,blackgrowlmon,flamedramon,tylomon|01|||||false`,
`Guilmon|guilmon_black|3|Reptile|3|||2|blackgrowlmon|01||03|||false`,
`Guilmon|guilmon_green|3|Reptile|3|||2||01||03|||false`,
`Guilmon|guilmon_extra|3|Reptile|3|||2||01||03|||false`,
`Guilmon|guilmon_extra_blue|3|Reptile|3|||2||01||03|||false`,
`Guilmon|guilmon_orange|3|Reptile|3|||2||01||03|||false`,
`Gummymon|gummymon|2|Lesser|2|||4|terriermon|01|||||false`,
`Gururumon|gururumon|4|Beast|4|||1||01|||||false`,
`Gururumon|gururumon_grey|4|Beast|4|||1||01||03|||false`,
`Gusokumon|gusokumon|5|Crustacean|5|||1||13|||||false`,
`Gwappamon|gwappamon|4|Cyborg|4|||3|shawjamon||||02|05|false`,
`Hackmon|hackmon|3|Mini Dragon|3|||3|baohuckmon||||02|18|false`,
`Hagurumon|hagurumon|3|Machine|3|||2|guardromon,mekanorimon,kongoumon|01|||||false`,
`Hagurumon|hagurumon_yellow|3|Machine|3|||2||01||03|||false`,
`Halsemon|halsemon|4|Bird|9|Love||4||01|||||false`,
`Harpymon|harpymon|4|Mythical Beast|9|Light||4||01|||||false`,
`Hawkmon|hawkmon|3|Avian|3|||4|aquilamon,allomon,rinkmon,halsemon,shurimon,flybeemon,orcamon,moosemon,harpymon,toucanmon,peacockmon|01|||||false`,
`HerculesKabuterimon|herculeskabuterimon|6|Insectoid|6|||1|tyrantkabuterimon|01|||||false`,
`HerculesKabuterimon|herculeskabuterimon_black|6|Insectoid|6|||1||01||03|||false`,
`Hexeblaumon|hexeblaumon|6|Magic Knight|6|||3|||||13|02|false`,
`HiAndromon|hiandromon|6|Cyborg|6|||1|craniamon|01|||||false`,
`HiMugendramon|himugendramon|6|Machine|6||TRUE|2||01||03|||false`,
`Hiyarimon|hiyarimon|2|Lesser|2|||4|bulucomon|03|||||false`,
`HolyDigitamamon|holydigitamamon|5|Perfect|5|||1|||||07|01|false`,
`HoneyBeemon|honeybeemon|4|Insectoid|9|Knowledge||4||08|||||false`,
`Hopmon|hopmon|2|Baby Dragon|2|||4|monodramon|01|||||false`,
`Huanglongmon|huanglongmon|7|Holy Dragon/Sovereigns|7||TRUE|3||02|||||false`,
`HustleNanimon|hustlenanimon|4||4|||2||01|03||||false`,
`Hyogamon|hyogamon|4|Ice-Snow|4|||2||01|||||false`,
`IceDevimon|icedevimon|4|Fallen Angel|4|||2|skullsatamon|01||03|||false`,
`IceDevimon|icedevimon_blue|4|Fallen Angel|4|||2||01||03|||false`,
`IceLeomon|iceleomon|5|Beastkin|5|||1|regulumon,saberleomon|01|||||false`,
`Icemon|icemon|4|Ice-Snow|4|||3|meteormon|01|||||false`,
`Ikkakumon|ikkakumon|4|Sea Beast|4|||1|zudomon|01|||||false`,
`Imperialdramon Dragon Mode|imperialdramon_dragon_mode|6|Ancient Dragon|6|||4|imperialdramon_fighter_mode|01|||||false`,
`Imperialdramon Dragon Mode|imperialdramon_dragon_mode_black|6|Ancient Dragon|6|||2|imperialdramon_fighter_mode_black|01||03|||false`,
`Imperialdramon Fighter Mode|imperialdramon_fighter_mode|6|Ancient Dragonkin|6|||4|imperialdramon_paladin_mode|03|||||false`,
`Imperialdramon Fighter Mode|imperialdramon_fighter_mode_black|6|Ancient Dragonkin|6|||2||03|||||false`,
`Imperialdramon Fighter Mode|imperialdramon_fighter_mode_yellow|6|Ancient Dragonkin|6|||4||03||03|||false`,
`Imperialdramon Paladin Mode|imperialdramon_paladin_mode|7|Ancient Dragonkin|7||TRUE|1||03|||||false`,
`Imperialdramon Paladin Mode|imperialdramon_paladin_mode_blue|7|Ancient Dragonkin|7||TRUE|1||03||03|||false`,
`Impmon|impmon|3|Evil|3|||2|devimon,icedevimon,meramon,wizardmon,thunderbirdmon,nohemon,quetzalmon|01|||||false`,
`Impmon|impmon_red|3|Evil|3|||2||01||03|||false`,
`Impmon|impmon_black|3|Evil|3|||2||01||03|||false`,
`Indramon|indramon|5|Holy Beast/Deva|5|||2||01|||||false`,
`Infermon|infermon|5|Unidentified|5|||5|diaboromon|01|||||false`,
`Jagamon|jagamon|5|Vegetation|5|||1||01|||||false`,
`Jesmon|jesmon|6|Holy Warrior/Royal Knight|6|||3|jesmon_gx|02|||||false`,
`Jesmon|jesmon_red|6|Holy Warrior|6|||3||02||03|||false`,
`JewelBeemon|jewelbeemon|5|Insectoid|5|||1|grankuwagamon|01|||||false`,
`Jijimon|jijimon|6|Ancient|6|||1||01|||||false`,
`Jijimon|jijimon_blue_staff|6|Ancient|6|||1||01||03|||false`,
`JungleMojyamon|junglemojyamon|4||4|||3||01|||||false`,
`Junomon|junomon|6|Shaman/Olympos XII|6|||2|junomon_hysteric_mode|13|||||false`,
`Junomon Hysteric Mode|junomon_hysteric_mode|6|Shaman/Olympos XII|6|||2||13|||||false`,
`Jupitermon|jupitermon|6|Shaman/Olympos XII|6|||1|jupitermon_wrath_mode|13|||||false`,
`Jupitermon Wrath Mode|jupitermon_wrath_mode|6|Shaman/Olympos XII|6|||1||13|||||false`,
`Justimon|justimon|6|Cyborg|6|||1|fujinmon|06|||||false`,
`Jyarimon|jyarimon|1|Slime|1|||4|gigimon,boltmon|01|||||false`,
`Kabuterimon|kabuterimon|4|Insectoid|4|||1|megakabuterimon,megakabuterimon_blue,kimeramon|01|||||false`,
`KaiserLeomon|kaiserleomon|4|Warrior|8|||6|rhihimon|07|||||false`,
`KaiserLeomon|kaiserleomon_white|4|Warrior|8|||6||07||03|||false`,
`Kakkinmon|kakkinmon|2|Armor|2|||4|ludomon|02|03||||false`,
`Kamemon|kamemon|3|Cyborg|3|||3|gwappamon|02|||||false`,
`Kapurimon|kapurimon|2|Lesser|2|||4|kokuwamon, kotemon|01|||||false`,
`Karatenmon|karatenmon|5|Wizard|5|||2|kuzuhamon|01|||||false`,
`Karatenmon|karatenmon_white|5|Wizard|5|||2||01|03||||false`,
`Kazemon|kazemon|4|Fairy|8|||6|zephyrmon|16|||||false`,
`Kazemon|kazemon_blue|4|Fairy|8|||6||16||03|||false`,
`Keemon|keemon|1|Slime|1|||4|yaamon|03|||||false`,
`KendoGarurumon|kendogarurumon|4|Cyborg|8|||6|beowolfmon|16|||||false`,
`KendoGarurumon|kendogarurumon_yellow|4|Cyborg|8|||6||16||03|||false`,
`Kenkimon|kenkimon|4|Machine|9|Friendship||3|bulbmon|01|||||false`,
`Kentaurosmon|kentaurosmon|6|Holy Warrior/Royal Knight|6|||1|ultimatechaosmon|02|||||false`,
`Keramon|keramon|3|Unidentified|3|||5|kurisarimon|01|||||false`,
`Ketomon|ketomon|1|Slime|1|||4|hopmon|01|||||false`,
`Kimeramon|kimeramon|5|Composite|5||TRUE|3|millenniummon|01|||||false`,
`KingEtemon|kingetemon|6|Puppet|6|||2||02|||||false`,
`KingSukamon|kingsukamon|4|Mutant|4|||2||01|03||||false`,
`KingWhamon|kingwhamon|5||5|||1|||||02|01|false`,
`Kiwimon|kiwimon|4|Ancient Bird|4|||3|sinduramon,blossomon|01|||||false`,
`Knightmon|knightmon|5|Warrior|5|||3|lordknightmon|01|||||false`,
`KoDokugumon|kodokugumon|2|Insectoid|2|||2|dokugumon|02||03|||false`,
`Kogamon|kogamon|4|Mutant|4|||3|cherrymon|01|||||false`,
`Kokatorimon|kokatorimon|4|Giant Bird|4|||3|sinduramon,megadramon|01|||||false`,
`Kokatorimon|kokatorimon_brown|4|Giant Bird|4|||3||01||03|||false`,
`Kokomon|kokomon|2|Lesser|2|||4|lopmon|01|||||false`,
`Kokuwamon|kokuwamon|3|Machine|3|||3|guardromon,thundermon,rhinomon|01|||||false`,
`Kongoumon|kongoumon|4|Insectoid|9|Miracles/Fate||3||08|||||false`,
`Korikakumon|korikakumon|4|Beast|8|||6|daipenmon|07|||||false`,
`Korikakumon|korikakumon_yellow|4|Beast|8|||6||07||03|||false`,
`Koromon|koromon|2|Lesser|2|||4|agumon,agumon_savers,agumon_movie|01|||||false`,
`Kotemon|kotemon|3|Reptile|3|||3|dinohyumon,kyukimon,musyamon,gladimon|01|||||false`,
`KoZenimon|kozenimon|2|Mutant|2|||4|zenimon|02|||||false`,
`Kudamon|kudamon|3|Holy Beast|3|||1||01|||||false`,
`Kudamon|kudamon_savers|3|Holy Beast|3|||1|reppamon|01|||||false`,
`Kumamon|kumamon|4|Beastkin|8|||6|korikakumon|07|||||false`,
`Kumamon|kumamon_orange|4|Beastkin|8|||6||07||03|||false`,
`Kumbhiramon|kumbhiramon|5|Holy Beast/Deva|5|||1||02|||||false`,
`Kunemon|kunemon|3|Larva|3|||2|flymon|01|||||false`,
`Kuramon|kuramon|1|Unidentified|1|||4|tsumemon|01|||||false`,
`Kurisarimon|kurisarimon|4|Unidentified|4|||5|infermon|01|||||false`,
`Kurisarimon|kurisarimon_red|4|Unidentified|4|||5||01||03|||false`,
`Kuwagamon|kuwagamon|4|Insectoid|4|||2|okuwagamon,megadramon,kimeramon|01|||||false`,
`Kuwagamon|kuwagamon_green|4|Insectoid|4|||2||01||03|||false`,
`Kuzuhamon|kuzuhamon|6|Shaman|6|||3||01|||||false`,
`Kuzuhamon Maid Mode|kuzuhamon_maid_mode|6|Shaman|6|||3||01|||||false`,
`Kyaromon|kyaromon|2|Lesser|2|||4||03|01||||false`,
`Kyokyomon|kyokyomon|2|Lesser|2|||4||02|03||||false`,
`Kyubimon|kyubimon|4|Mysterious Beast|4|||3|taomon|01|||||false`,
`Kyubimon|kyubimon_silver|4|Mysterious Beast|4|||1|taomon_silver|01||03|||false`,
`Kyupimon|kyupimon|2|Mini Angel|2|||4||03|||||false`,
`Labramon|labramon|3|Beast|3|||1|seasarmon,dobermon|01||03|||false`,
`Labramon|labramon_brown|3|Beast|3|||1||01|||||false`,
`LadyDevimon|ladydevimon|5|Fallen Angel|5|||2|skullsatamon,myotismon,minervamon,mastemon,apocalymon|01|||||false`,
`LadyDevimon|ladydevimon_red|5|Fallen Angel|5|||2||01||03|||false`,
`Lalamon|lalamon|3|Vegetation|3|||3|sunflowmon|02|03||||false`,
`Lavogaritamon|lavogaritamon|5|Rock Dragon|5|||2|volcanicdramon|02|||||false`,
`Lavorvomon|lavorvomon|4|Rock Dragon|4|||2|lavogaritamon|02|||||false`,
`Leafmon|leafmon|1|Slime|1|||4|minomon|01|||||false`,
`Leomon|leomon|4|Beastkin|4|||1|iceleomon,grapleomon|01|||||false`,
`Leopardmon|leopardmon|6|Holy Warrior/Royal Knight|6|||3|leopardmon_leopard_mode||||12|05|false`,
`Leopardmon Leopard Mode|leopardmon_leopard_mode|6|Holy Warrior/Royal Knight|6|||3||11|||||false`,
`Leviamon|leviamon|6|Demon Lord/Seven Great Demon Lords|6|||2|ogudomon|02|||||false`,
`Leviamon|leviamon_black|6|Demon Lord/Seven Great Demon Lords|6|||2||02||03|||false`,
`LightToyAgumon|lighttoyagumon|3|Puppet|3|||1||01||03|||false`,
`Lilamon|lilamon|5|Fairy|5|||3|rosemon,lotosmon|06||03|||false`,
`Lilithmon|lilithmon|6|Demon Lord/Seven Great Demon Lords|6|||2|ogudomon|01|||||false`,
`Lilithmon|lilithmon_red|6|Demon Lord/Seven Great Demon Lords|6|||2||01||03|||false`,
`Lillymon|lillymon|5|Fairy|5|||3|rosemon,marineangemon,bancholillymon|01|||||false`,
`Liollmon|liollmon|3|Holy Beast|3|||1|liamon||||03|13|false`,
`Lobomon|lobomon|4|Warrior|8|||6|kendogarurumon|16|||||false`,
`Lobomon|lobomon_yellow|4|Warrior|8|||6||16||03|||false`,
`Lobomon|lobomon_extra|4|Warrior|8|||6||16||03|||false`,
`Lobomon|lobomon_extra_yellow|4|Warrior|8|||6||16||03|||false`,
`Lopmon|lopmon|3|Beast|3|||3|wendigomon,turuiemon,rapidmon_gold|01|||||false`,
`Lopmon|lopmon_blue|3|Beast|3|||3||01||03|||false`,
`LordKnightmon|lordknightmon|6|Holy Warrior/Royal Knight|6|||2||02|||||false`,
`Loweemon|loweemon|4|Warrior|8|||6|kaiserleomon|07|||||false`,
`Loweemon|loweemon_white|4|Warrior|8|||6||07||03|||false`,
`Lucemon|lucemon|3|Angel|3|||1|lucemon_chaos_mode|03|||||false`,
`Lucemon Chaos Mode|lucemon_chaos_mode|5|Demon Lord/Seven Great Demon Lords|5|||2|lucemon_larva,ogudomon||||02|10|false`,
`Lucemon Larva|lucemon_larva|6|Demon Lord/Larva|6|||2|lucemon_shadowlord_mode|||03|02|10|false`,
`Lucemon Shadowlord Mode|lucemon_shadowlord_mode|7|Demon Lord|7|||2||13|||||false`,
`Lucemon Shadowlord Mode|lucemon_shadowlord_mode_gold|7|Demon Lord|7|||2||13||03|||false`,
`Lynxmon|lynxmon|4|Beast|9|Courage||4||01|||||false`,
`MachGaogamon|machgaogamon|5|Cyborg|5|||3|miragegaogamon,zeedgarurumon|02|||||false`,
`Machinedramon|machinedramon|6|Machine|6||TRUE|2|millenniummon,chaosdramon|01|||||false`,
`Machinedramon|machinedramon_white|6|Machine|6||TRUE|2||01||03|||false`,
`MagnaAngemon|magnaangemon|5|Archangel|5|||1|seraphimon,dominimon,murmukusmon|01|||||false`,
`MagnaAngemon Priest Mode|magnaangemon_priest_mode|5|Archangel|5|||1|seraphimon,dominimon,murmukusmon|01|||||false`,
`Magnadramon|magnadramon|6|Holy Dragon/Four Great Dragons|6|||1||01|||||false`,
`Magnadramon|magnadramon_green|6|Holy Dragon/Four Great Dragons|6|||1||01||03|||false`,
`Magnamon|magnamon|6|Holy Warrior/Royal Knight|9|Miracles||4||16|02|03|||false`,
`Magnamon|magnamon_black|6|Holy Warrior|9|Miracles||4||16|02|03|||false`,
`MailBirdramon|mailbirdramon|4|Machine|4|||3||02|||||false`,
`Maildramon|maildramon|4|Cyborg|9|Miracles/Fate||4||08|03||||false`,
`Maildramon|maildramon_virus|4|Cyborg|4|||2||08|03||||false`,
`Maildramon|maildramon_black|4|Cyborg|9|Miracles/Fate||4||08|03|03|||false`,
`Majiramon|majiramon|5|Holy Dragon/Deva|5|||3||01|||||false`,
`Makuramon|makuramon|5|Holy Beast/Deva|5|||3||07|||||false`,
`MaloMyotismon|malomyotismon|6|Demon Lord|6|||2|||||||false`,
`Mamemon|mamemon|5|Mutant|5|||3|metalmamemon,tonosamamamemon,princemamemon,bigmamemon,catchmamemon,machinedramon|01|||||false`,
`MameTyramon|mametyramon|5|Small Tyranny|5|||3|dinorexmon|08|||||false`,
`Mammothmon|mammothmon|5|Ancient Animal|5|||1|skullmammothmon|01|||||false`,
`Mammothmon|mammothmon_grey|5|Ancient Animal|5|||1||01||03|||false`,
`Manbomon|manbomon|4|Mutant|9|Light||1||02|||||false`,
`Mantaraymon|mantaraymon|4|Sea Animal|9|Sincerity||4||13|||||false`,
`MarinChimairamon|marinchimairamon|5|Composite|5||TRUE|1||13|||||false`,
`MarineAngemon|marineangemon|6|Fairy|6|||1||01|||||false`,
`MarineDevimon|marinedevimon|5|Sea Animal|5|||2|leviamon,skullsatamon,myotismon|01|||||false`,
`Marsmon|marsmon|6|Shaman/Olympos XII|6|||1||13|||||false`,
`MasterTyrannomon|mastertyrannomon|5|Dinosaur|5|||1|samudramon|01|||||false`,
`MasterTyrannomon|mastertyrannomon_black|5|Dinosaur|5|||1||01||03|||false`,
`MasterVeedramon|masterveedramon|4|Mythical Dragon|4|||1||01||03|||false`,
`Matadormon|matadormon|5|Undead|5|||2|grandracmon,beelzemon||||02|14|false`,
`MedievalGallantmon|medievalgallantmon|6|Warrior|6|||3||12|||||false`,
`Megadramon|megadramon|5|Cyborg|5|||2|ghoulmon,machinedramon|01|||||false`,
`MegaGargomon|megagargomon|6|Machine|6|||1||01|||||false`,
`MegaGargomon|megagargomon_grey|6|Machine|6|||1||01||03|||false`,
`MegaKabuterimon|megakabuterimon|5|Insectoid|5|||1|herculeskabuterimon,grankuwagamon|01|||||false`,
`MegaKabuterimon|megakabuterimon_blue|5|Insectoid|5|||3|ancientbeetlemon,herculeskabuterimon|01|||||false`,
`MegaSeadramon|megaseadramon|5|Sea Animal|5|||3|metalseadramon|01|||||false`,
`MegaSeadramon|megaseadramon_orange|5|Sea Animal|5|||3||01||03|||false`,
`Megidramon|megidramon|6|Evil Dragon/Four Great Dragons|6|||2||01|||||false`,
`Mekanorimon|mekanorimon|4|Machine|4|||2|megadramon|01|||||false`,
`Mephistomon|mephistomon|5|Evil|5|||2|gulfmon|13||03|||false`,
`Meramon|meramon|4|Flame|4|||3|bluemeramon,skullmeramon|01|||||false`,
`Mercurimon|mercurimon|6|Shaman/Olympos XII|6|||2||13|||||false`,
`Mercurymon|mercurymon|4|Mutant|8|||6|sakkakumon,shadowseraphimon|07|||||false`,
`Mermaimon|mermaimon|5||5|||3||13|02||||false`,
`Mervamon|mervamon|6|Shaman/Olympos XII|6|||2||13|||||false`,
`MetalEtemon|metaletemon|6|Cyborg|6|||2|kingetemon|01|||||false`,
`MetalGarurumon|metalgarurumon|6|Cyborg|6|||1|omnimon,omnimon_zwart|01|||||false`,
`MetalGarurumon|metalgarurumon_black|6|Cyborg|6|||2|omnimon_zwart|01|||||false`,
`MetalGarurumon|metalgarurumon_white|6|Cyborg|6|||1||01||03|||false`,
`MetalGarurumon|metalgarurumon_red|6|Cyborg|6|||1||01||03|||false`,
`MetalGreymon|metalgreymon|5|Cyborg|5|||1|wargreymon,ancientgreymon,blackwargreymon,samudramon,blitzgreymon,victorygreymon|01|||||false`,
`MetalGreymon|metalgreymon_blue|5|Cyborg|5|||2|blackwargreymon,blitzgreymon|01|||||false`,
`MetalKabuterimon|metalkabuterimon|4|Cyborg|8|||6|rhinokabuterimon|16|||||false`,
`MetalKabuterimon|metalkabuterimon_red|4|Cyborg|8|||6||16||03|||false`,
`MetalKoromon|metalkoromon|1|Machine|1|||4|hagurumon,kapurimon|01|||||false`,
`MetalMamemon|metalmamemon|5|Cyborg|5|||3|princemamemon,machinedramon|01|||||false`,
`MetalPiranimon|metalpiranimon|6|Sea Animal/X-Antibody|6|||2||13|||||false`,
`MetalSeadramon|metalseadramon|6|Cyborg|6|||3|gigaseadramon|01|||||false`,
`MetalSeadramon|metalseadramon_black|6|Cyborg|6|||3||01||03|||false`,
`MetalTyrannomon|metaltyrannomon|5|Cyborg|5|||2|rusttyranomon,machinedramon||||02|01|false`,
`Meteormon|meteormon|5|Rock|5|||3|ancientvolcanomon,metaletemon|01|||||false`,
`Meteormon|meteormon_brown|5|Rock|5|||3||01||03|||false`,
`Mihiramon|mihiramon|5|Holy Beast/Deva|5|||3||08|||||false`,
`Mikemon|mikemon|4|Beast|4|||3|beastmon|01|||||false`,
`Millenniummon|millenniummon|7|Composite|7||TRUE|2|moonmillenniummon|02||03|||false`,
`Minervamon|minervamon|6|Shaman/Olympos XII|6|||2|mervamon|13|||||false`,
`Minomon|minomon|2|Larva|2|||4|wormmon|01|||||false`,
`Minotarumon|minotarumon|4|Beastkin|4|||2||01|||||false`,
`MirageGaogamon|miragegaogamon|6|Beast Knight|6|||3|miragegaogamon_burst_mode|09|||||false`,
`MirageGaogamon Burst Mode|miragegaogamon_burst_mode|6|Beast Knight|6|||3|||||03|09|false`,
`Missimon|missimon|2|Machine|2|||4||06|||||false`,
`Mistymon|mistymon|5|Magic Warrior|5|||2|dynasmon|01|||||false`,
`ModokiBetamon|modokibetamon|3|Amphibian|3|||3||01|||||false`,
`Mojyamon|mojyamon|4||4|||1|piximon|01|||||false`,
`Mokumon|mokumon|1|Smoke|1|||4|demimeramon|01|||||false`,
`Monimon|monimon|2||2|||4||03|||||false`,
`Monimon|monimon_super|2||2|||4||03|||||false`,
`Monitamon|monitamon|3|CRT|3|||3||02|03||||false`,
`Monitamon|monitamon_grey|3|CRT|3|||3||02|03|03|||false`,
`Monitamon|monitamon_pink|3|CRT|3|||3||02|03|03|||false`,
`Monitamon|monitamon_purple|3|CRT|3|||3||02|03|03|||false`,
`Monitamon|monitamon_red|3|CRT|3|||3||02|03|03|||false`,
`Monitamon|monitamon_yellow|3|CRT|3|||3||02|03|03|||false`,
`Monmon|monmon|3|Beast|3|||1|armormon|01|||||false`,
`Monochromon|monochromon|4|Ankylosaur|4|||3|megadramon,kimeramon|01|||||false`,
`Monodramon|monodramon|3|Mini Dragon|3|||1|strikedramon,devidramon,airdramon,megadramon,kabukimon,depthmon|01|||||false`,
`Monzaemon|monzaemon|5|Puppet|5|||1|lilithmon,minervamon|01|||||false`,
`Moonmon|moonmon|2|Lesser|2|||1|lunamon||||03|02|false`,
`Moosemon|moosemon|4|Ancient Animal|9|Hope||4|||||02|01|false`,
`MoriShellmon|morishellmon|4|Mollusk|4|||3||01|||||false`,
`Morphomon|morphomon|3|Insectoid|3|||1|eosmon_champion|13|03||||false`,
`Mothmon|mothmon|4|Insectoid|9|Knowledge||4||08||03|||false`,
`Motimon|motimon|2|Lesser|2|||4|tentomon,dokunemon|01|||||false`,
`Motimon|motimon_yellow|2|Lesser|2|||4||01||03|||false`,
`Muchomon|muchomon|3|Avian|3|||3|sinduramon|01|||||false`,
`MudFrigimon|mudfrigimon|4|Mutant|4|||3|pandamon|01|||||false`,
`MudFrigimon|mudfrigimon_no_buttons|4|Mutant|4|||3||01|03||||false`,
`Mushroomon|mushroomon|3|Vegetation|3|||2|woodmon|01|||||false`,
`Musyamon|musyamon|4|Wizard|4|||2|asuramon|01|||||false`,
`Musyamon|musyamon_green|4|Wizard|4|||2||01||03|||false`,
`Myotismon|myotismon|5|Undead|5|||2|venommyotismon,apocalymon,boltboutamon,barbamon|01|||||false`,
`Myotismon|myotismon_purple|5|Undead|5|||2||01||03|||false`,
`Nanimon|nanimon|4||4|||2||01|||||false`,
`Neemon|neemon|3|Beast|3|||3||01|||||false`,
`Nefertimon|nefertimon|4|Holy Beast|9|Light||1||01|||||false`,
`NeoDevimon|neodevimon|5|Fallen Angel|5|||2|daemon_mantled,donedevimon|01|||||false`,
`Neptunemon|neptunemon|6|Shaman/Olympos XII|6|||1||13|||||false`,
`Ninjamon|ninjamon|4|Mutant|4|||2|blossomon,cherrymon|01|||||false`,
`NiseDrimogemon|nisedrimogemon|4|Beast|4|||1||01|||||false`,
`NoblePumpkinmon|noblepumpkinmon|6|Puppet|6|||3||13|||||false`,
`Numemon|numemon|4|Mollusk|4|||2|monzaemon|01|||||false`,
`Numemon|numemon_blue|4|Mollusk|4|||2||01||03|||false`,
`Numemon|numemon_brown|4|Mollusk|4|||2||01||03|||false`,
`Numemon|numemon_light_blue|4|Mollusk|4|||2||01||03|||false`,
`Numemon|numemon_red|4|Mollusk|4|||2||01||03|||false`,
`Numemon|numemon_teal|4|Mollusk|4|||2||01||03|||false`,
`Nyaromon|nyaromon|2|Lesser|2|||4|salamon|01|||||false`,
`Nyaromon|nyaromon_unknown|2|Lesser|2|||4|salamon_unknown|01||03|||false`,
`Nyokimon|nyokimon|1|Seed|1|||4|yokomon|01|||||false`,
`Octomon|octomon|4|Mollusk|4|||2||01|||||false`,
`Ogremon|ogremon|4|Demon|4|||2|weregarurumon_black,skullsatamon,etemon,digitamamon|01|||||false`,
`Okuwamon|okuwamon|5|Insectoid|5|||2|grankuwagamon|01|||||false`,
`Omnimon|omnimon|7|Holy Warrior/Royal Knight|7||TRUE|1|omnimon_merciful_mode,imperialdramon_paladin_mode|02|||||false`,
`Omnimon|omnimon_blue|7|Holy Warrior/Royal Knight|7||TRUE|1||02||03|||false`,
`Omnimon|omnimon_black|7|Holy Warrior/Royal Knight|7||TRUE|1||02|||||false`,
`Omnimon Alter-B|omnimon_alter_b|7|Holy Warrior|7||TRUE|2||02|03||||false`,
`Omnimon Alter-S|omnimon_alter_s|7|Holy Warrior|7||TRUE|2||02|||||false`,
`Omnimon Merciful Mode|omnimon_merciful_mode|7|Holy Warrior|7|||1||02|||||false`,
`Omnimon Zwart|omnimon_zwart|7|Holy Warrior|7||TRUE|2|omnimon_zwart_d|02||03|||false`,
`Omnimon Zwart Defeat|omnimon_zwart_defeat|7|Holy Warrior|7|||2|||||03|02|false`,
`OmniShoutmon|omnishoutmon|5|Dragonkin|5|||3||02|14||||false`,
`Ophanimon|ophanimon|6|Throne/Three Great Angels|6|||1|ophanimon_core,ophanimon_falldown_mode|01|||||false`,
`Ophanimon|ophanimon_green|6|Throne/Three Great Angels|6|||1||01|||||false`,
`Ophanimon Core|ophanimon_core|6|Throne/Core|6|||1||01||03|||false`,
`Ophanimon Falldown Mode|ophanimon_falldown_mode|6|Fallen Angel|6|||1||13|||||false`,
`Opossummon|opossummon|4|Beast|9|Kindness||4|chohakkaimon|07|||||true`,
`Orcamon|orcamon|4|Sea Animal|9|Sincerity||4||08|||||false`,
`Ornismon|ornismon|6|Ancient Bird|6|||2||02|||||false`,
`Orochimon|orochimon|5|Dark Animal|5|||2|ebonwumon,nidhoggmon|02|||||false`,
`Oryxmon|oryxmon|4|Mammal|9|Hope||4||01|||||false`,
`Otamamon|otamamon|3|Amphibian|3|||2|gekomon,tylomon,manbomon|01|||||false`,
`Otamamon|otamamon_red|3|Amphibian|3|||3||01|||||false`,
`Ouryumon|ouryumon|6|Dragon|6|||1|alphamon_ouryuken|02|10||||false`,
`Pabumon|pabumon|1|Slime|1|||4|tanemon,motimon|01|||||false`,
`Pafumon|pafumon|1|Spirit|1|||4|kyaromon|03|||||false`,
`Pagumon|pagumon|2|Lesser|2|||4|agumon_black,gotsumon,goblimon,demidevimon,gizamon|01|||||false`,
`Paildramon|paildramon|5|Dragonkin|5||TRUE|4|imperialdramon_dragon_mode|01|||||false`,
`Pajiramon|pajiramon|5|Holy Beast/Deva|5|||2||02|10||||false`,
`Paledramon|paledramon|4|Dragon|4|||3|cryspaledramon|02|||||false`,
`Palmon|palmon|3|Vegetation|3|||3|togemon,woodmon|01|||||false`,
`Pandamon|pandamon|5|Puppet|5|||3|bancholeomon|01|||||false`,
`Paomon|paomon|1|Slime|1|||4|xiaomon|01||03|||false`,
`Paomon|paomon_brown|1|Slime|1|||4||01|||||false`,
`Parasaurmon|parasaurmon|4|Dinosaur|4|||2||18|||||false`,
`Parrotmon|parrotmon|5|Bird|5|||1|eaglemon|01|||||false`,
`Patamon|patamon|3|Mammal|3|||3|angemon,baromon,stegomon,pipismon,ponchomon,mothmon,mantaraymon,pegasusmon,manbomon,prairiemon,rhinomon|01|||||false`,
`Patamon|patamon_pink|3|Mammal|3|||3||01||03|||false`,
`Patamon|patamon_blue|3|Mammal|3|||3||01||03|||false`,
`Peckmon|peckmon|4|Bird|4|||1|crowmon,pteramon||||02|07|false`,
`Peckmon|peckmon_blue|4|Bird|4|||1||||03|02|07|false`,
`Pegasusmon|pegasusmon|4|Holy Beast|9|Hope||1||01|||||false`,
`Penguinmon|penguinmon|3|Avian|3|||1|dolphmon|01|||||false`,
`Petaldramon|petaldramon|4|Vegetation|8|||6||07|||||false`,
`Petitmon|petitmon|1|Slime|1|||4|babydmon|03|||||false`,
`Phantomon|phantomon|5|Ghost|5|||2|metalphantomon,piedmon,dynasmon|01|||||false`,
`Phantomon|phantomon_purple|5|Ghost|5|||2||01||03|||false`,
`Pharaohmon|pharaohmon|6|Ghost|6|||2||02|||||false`,
`Phoenixmon|phoenixmon|6|Holy Beast|6|||1|varodurumon,ornismon|01|||||false`,
`Pichimon|pichimon|1|Slime|1|||4|bukamon,marineangemon|01|||||false`,
`Pickmon|pickmon|2|Minor|2|||4|starmon_fusion|02|||||false`,
`Pickmon|pickmon_yellow|2|Minor|2|||4||02|||||false`,
`Pickmon|pickmon_red|2|Minor|2|||4||02|||||false`,
`Pickmon|pickmon_super|2|Minor|2|||4||02|||||false`,
`Piddomon|piddomon|4|Angel|4|||1||01|||||false`,
`Piedmon|piedmon|6|Wizard|6|||2|apocalymon,boltboutamon|01|||||false`,
`Pinamon|pinamon|2||2|||4||03|01||||false`,
`Pipismon|pipismon|4|Mutant|9|Love||4||15|||||false`,
`Piranimon|piranimon|5|Sea Animal|5|||2|metalpiranimon|13|||||false`,
`Piximon|piximon|5|Fairy|5|||3|jijimon|01|||||false`,
`PlatinumNumemon|platinumnumemon|6|Mutant|6|||2||01|||||false`,
`PlatinumSukamon|platinumsukamon|4|Mutant|4|||2||01|||||false`,
`Plesiomon|plesiomon|6|Plesiosaur|6|||1|aegisdramon|01|||||false`,
`Plesiomon|plesiomon_blue|6|Plesiosaur|6|||1||01||03|||false`,
`Plutomon|plutomon|6|Shaman|6|||2||13|||||false`,
`Pomumon|pomumon|3|Vegetation|3|||3||21|03|03|||false`,
`Ponchomon|ponchomon|4|Mutant|9|Purity||4||02|||||false`,
`Popomon|popomon|1|Slime|1|||4|frimon||||03|06|false`,
`Poromon|poromon|2|Mini Bird|2|||4|hawkmon|01|||||false`,
`Poyomon|poyomon|1|Slime|1|||4|tokomon,bukamon|01|||||false`,
`Prairiemon|prairiemon|4|Beast|9|Kindness||4|antylamon_deva|08|||||false`,
`PrinceMamemon|princemamemon|6|Mutant|6|||3||01|||||false`,
`Psychemon|psychemon|3|Reptile|3|||3||01||03|||false`,
`Pteramon|pteramon|4|Dinosaur|9|Love||4||18|||||false`,
`Pukumon|pukumon|6|Mutant|6|||2||01|||||false`,
`Pumpkinmon|pumpkinmon|5|Puppet|5|||3|boltmon,noblepumpkinmon|01|||||false`,
`Punimon|punimon|1|Slime|1|||4|tsunomon,salamon|01|||||false`,
`Puppetmon|puppetmon|6|Puppet|6|||2|ancienttroiamon|01|||||false`,
`Pupumon|pupumon|1|Slime|1|||4|puroromon|03|||||false`,
`Puroromon|puroromon|2|Larva|2|||4|fanbeemon|03|||||false`,
`Pururumon|pururumon|1|Slime|1|||4|poromon|01|||||false`,
`Pusumon|pusumon|1|Slime|1|||4|pusurimon|02|||||false`,
`Pusurimon|pusurimon|2|Lesser|2|||4|herissmon|02|||||false`,
`Puttimon|puttimon|1|Mini Angel|1|||4|kyupimon|06|03||||false`,
`Puwamon|puwamon|1||1|||4|pinamon|06|||||false`,
`Quetzalmon|quetzalmon|4|Mythical Beast|9|Light||4||01|||||false`,
`Rafflesimon|rafflesimon|6|Fairy|6||TRUE|3||13|||||false`,
`Raidramon|raidramon|4|Beast|9|Friendship||4||01|||||false`,
`Ranamon|ranamon|4|Fairy|8|||6|calmaramon|07|||||false`,
`Rapidmon|rapidmon|5|Cyborg|5|||1|megagargomon|01|||||false`,
`Rapidmon|rapidmon_gold|6|Holy Warrior|9|Fate||1||01|||||false`,
`Raremon|raremon|4|Undead|4|||2|skullsatamon|01|||||false`,
`Raremon|raremon_red|4|Undead|4|||2||01||03|||false`,
`Ravemon|ravemon|6|Cyborg|6|||1|ravemon_burst_mode||||03|08|false`,
`Ravemon Burst Mode|ravemon_burst_mode|6|Cyborg|6|||1|||||03|08|false`,
`Reapermon|reapermon|6|Cyborg|6|||2||02|||||true`,
`RedVeedramon|redveedramon|4|Mythical Dragon|4|||2||01||03|||false`,
`RedVegiemon|redvegiemon|4|Carnivorous Plant|4|||2||01|||||false`,
`RedVegiemon|redvegiemon_orange|4|Carnivorous Plant|4|||2||01||03|||false`,
`Regalecusmon|regalecusmon|6|Sea Animal|6|||2|||||13|02|false`,
`Regulumon|regulumon|6|Beastkin|6|||1||01||03|||false`,
`Relemon|relemon|1|Slime|1|||4|viximon|01|||||false`,
`Renamon|renamon|3|Beastkin|3|||3|kyubimon,youkomon,raidramon|01|||||false`,
`Renamon|renamon_red|3|Beastkin|3|||3||01||03|||false`,
`Renamon|renamon_silver|3|Beastkin|3|||3||01||03|||false`,
`Reppamon|reppamon|4|Holy Beast|4|||1|chirinmon|07|||||false`,
`Rhihimon|rhihimon|5|Warrior|8||TRUE|6||07|||||false`,
`Rhinomon|rhinomon|4|Mammal|9|Miracles/Fate||1||13|||||false`,
`Rinkmon|rinkmon|4|Cyborg|9|Friendship||4||07|||||false`,
`RizeGreymon|rizegreymon|5|Cyborg|5|||1|shinegreymon,victorygreymon,samudramon||||02|01|false`,
`Roachmon|roachmon|4|Insectoid|4|||2||01|||||false`,
`Rosemon|rosemon|6|Fairy|6|||3|babamon,rosemon_burst_mode,rafflesimon|01|||||false`,
`Rosemon Burst Mode|rosemon_burst_mode|6|Fairy|6|||3||01|||||false`,
`RustTyranomon|rusttyranomon|6|Cyborg|6|||2||02|||||false`,
`Saberdramon|saberdramon|4|Giant Bird|4|||2||01||03|||false`,
`Saberdramon|saberdramon_blue|4|Giant Bird|4|||2||01||03|||false`,
`SaberLeomon|saberleomon|6|Ancient Animal|6|||1|dinotigermon|01|||||false`,
`Sagittarimon|sagittarimon|4|Mythical Beast|9|Hope||1||07|||||false`,
`Sakkakumon|sakkakumon|4|Mutant|8|||6||07|||||false`,
`Sakumon|sakumon|1|Weapon|1|||4|sakuttomon|02|||||false`,
`Sakuttomon|sakuttomon|2|Weapon|2|||4|zubamon|02|||||false`,
`Sakuyamon|sakuyamon|6|Shaman|6|||3||01|||||false`,
`Sakuyamon|sakuyamon_red|6|Shaman|6|||3||01||03|||false`,
`Sakuyamon|sakuyamon_silver|6|Shaman|6|||3||01||03|||false`,
`Sakuyamon Maid Mode|sakuyamon_maid_mode|6|Shaman|6|||3||01|||||false`,
`Salamandermon|salamandermon|4|Amphibian|9|Courage||2||02|14||||false`,
`Salamon|salamon|3|Mammal|3|||1|gatomon,blackgatomon,mikemon,rabbitmon,oryxmon,nefertimon,opossummon,maildramon|01|||||false`,
`Salamon|salamon_unknown|3|Mammal|3|||1|meicoomon|01||03|||false`,
`Sandiramon|sandiramon|5|Holy Beast/Deva|5|||2||02|||||false`,
`SandYanmamon|sandyanmamon|4|Insectoid|4|||2||01|||||false`,
`Sangloupmon|sangloupmon|4||4|||2|matadormon|10|02||||false`,
`Sangomon|sangomon|3|Mollusk|3|||2||13|||||false`,
`Sanzomon|sanzomon|5|Monk|5|||1||13|||||false`,
`SaviorHuckmon|saviorhuckmon|5|Dragonkin|5|||3|jesmon|02|||||false`,
`Scorpiomon|scorpiomon|5|Crustacean|5|||3||01|||||false`,
`Scorpiomon|scorpiomon_black|5|Crustacean|5|||3||01||03|||false`,
`Seadramon|seadramon|4|Sea Animal|4|||3|megaseadramon,mamemon,whamon,waruseadramon|01|||||false`,
`Seadramon|seadramon_brown|4|Sea Animal|4|||3||01||03|||false`,
`Seahomon|seahomon|4|Sea Animal|9|Light||4||08|||||false`,
`Seasarmon|seasarmon|4|Holy Beast|4|||1||01|||||false`,
`Seraphimon|seraphimon|6|Seraph/Three Great Angels|6|||1||01|||||false`,
`Seraphimon|seraphimon_orange|6|Seraph/Three Great Angels|6|||1||01||03|||false`,
`Seraphimon|seraphimon_grey|6|Seraph/Three Great Angels|6|||1||01||03|||false`,
`Sethmon|sethmon|4|Dark Animal|9|Love||4||07|||||false`,
`ShadowSeraphimon|shadowseraphimon|6|Fallen Angel|6|||2|daemon_mantled|01|||||false`,
`ShadowToyAgumon|shadowtoyagumon|3|Puppet|3|||2|guardromon|01||03|||false`,
`Shadramon|shadramon|4|Insectoid|9|Courage||2||01|||||false`,
`Shakkoumon|shakkoumon|5|Mutant|5|||4|clavisangemon,vikemon,slashangemon|01|||||false`,
`Shamanmon|shamanmon|3|Demon|3|||2|apemon|01|||||false`,
`Shamanmon|shamanmon_brown|3|Demon|3|||2||01||03|||false`,
`Shawjamon|shawjamon|5|Demon|5|||2|jumbogamemon|02|||||false`,
`Sheepmon|sheepmon|4|Mammal|9|Hope||4|||||02|15|false`,
`Shellmon|shellmon|4|Mollusk|4|||3||01|||||false`,
`ShellNumemon|shellnumemon|4|Crustacean|4|||2||01|||||false`,
`ShimaUnimon|shimaunimon|4|Mythical Beast|4|||1||01|||||false`,
`ShineGreymon|shinegreymon|6|Light Dragon|6|||1|shinegreymon_burst_mode,shinegreymon_ruin_mode|19|||||false`,
`ShineGreymon|shinegreymon_black|6|Light Dragon|6|||1||19||03|||false`,
`ShineGreymon Burst Mode|shinegreymon_burst_mode|6|Light Dragon|6|||1|||||02|19|false`,
`ShineGreymon Ruin Mode|shinegreymon_ruin_mode|6|Light Dragon|6|||1|||||02|19|false`,
`ShogunGekomon|shogungekomon|5|Amphibian|5|||2|pukumon|01|||||false`,
`ShogunGekomon|shogungekomon_blue|5|Amphibian|5|||2||01||03|||false`,
`Shoutmon|shoutmon|3|Mini Dragon|3|||3|shoutmon_king|03|||||false`,
`Shoutmon|shoutmon_blue|3|Mini Dragon|3|||3||03|||||false`,
`Shoutmon|shoutmon_black|3|Mini Dragon|3|||3||03|||||false`,
`Shoutmon|shoutmon_yellow|3|Mini Dragon|3|||3||03|||||false`,
`Shurimon|shurimon|4|Mutant|9|Purity||4||01|||||false`,
`Shurimon|shurimon_blue|4|Mutant|9|Purity||4||01||03|||false`,
`Silphymon|silphymon|5|Beastkin|5|||4|dynasmon,valkyrimon,varodurumon,phoenixmon|01|||||false`,
`Sinduramon|sinduramon|5|Holy Bird/Deva|5|||3|varodurumon|02|||||false`,
`Sirenmon|sirenmon|5|Shaman|5|||3||13|||||false`,
`SkullBaluchimon|skullbaluchimon|5|Undead/X-Antibody|5|||3||13|||||false`,
`SkullGreymon|skullgreymon|5|Undead|5|||2|blackwargreymon,machinedramon|01|||||false`,
`SkullMammothmon|skullmammothmon|6|Undead|6|||1|||||02|10|false`,
`SkullMeramon|skullmeramon|5|Flame|5|||3|boltmon,beelzemon,gankoomon|01|||||false`,
`SkullSatamon|skullsatamon|5|Undead|5|||2|beelzemon,apocalymon,murmukusmon,daemon_mantled|01|||||false`,
`SkullScorpiomon|skullscorpiomon|5|Insectoid|5|||2|||||02|05|false`,
`SlashAngemon|slashangemon|6|Authority|6|||1||01|||||false`,
`Slayerdramon|slayerdramon|6|Dragonkin|6|||1|examon|20|03||||false`,
`Snimon|snimon|4|Insectoid|4|||1||01|||||false`,
`Snimon|snimon_orange|4|Insectoid|4|||1||01||03|||false`,
`SnowAgumon|snowagumon|3|Reptile|3|||1||01|||||false`,
`SnowAgumon|snowagumon_savers|3|Dinosaur|3|||1|||||03|01|false`,
`SnowBotamon|snowbotamon|1|Slime|1|||4|nyaromon,hiyarimon|01|||||false`,
`SnowGoblimon|snowgoblimon|3|Demon|3|||2||01|03||||false`,
`Solarmon|solarmon|3|Machine|3|||1|clockmon,guardromon_gold,meramon,kenkimon|01|||||false`,
`Sorcerymon|sorcerymon|4|Wizard|4|||1||01|||||false`,
`Soulmon|soulmon|4|Ghost|4|||2|phantomon|01|||||false`,
`Spinomon|spinomon|6|Dinosaur|6|||2||02|||||true`,
`Starmon|starmon|4|Mutant|4|||3|superstarmon|01|||||false`,
`Starmon|starmon_fusion|3|Major|3|||3||02||03|||false`,
`Stegomon|stegomon|4|Dinosaur|9|Friendship||4|||||02|01|false`,
`Stingmon|stingmon_black|4|Insectoid|4|||4||01||03|||false`,
`Stingmon|stingmon|4|Insectoid|4|||4|paildramon,dinobeemon,jewelbeemon,kongoumon|01|||||false`,
`Stingmon|stingmon_red|4|Insectoid|4|||4||01||03|||false`,
`Stingmon|stingmon_teal|4|Insectoid|4|||4||01||03|||false`,
`Strabimon|strabimon|3|Beastkin|8|||6|lobomon|03|||||false`,
`Strikedramon|strikedramon|4|Dragonkin|4|||1|cyberdramon|01|||||false`,
`Submarimon|submarimon|4|Sea Animal|9|Sincerity||4||01|||||false`,
`Sukamon|sukamon|4|Mutant|4|||2|etemon,kingsukamon|01|||||false`,
`Sukamon|sukamon_purple|4|Mutant|4|||2||01||03|||false`,
`Sunamon|sunamon|1|Slime|1|||4|goromon|03|||||false`,
`Sunarizamon|sunarizamon|3|Reptile|3|||2||13|||||false`,
`Sunflowmon|sunflowmon|4|Vegetation|4|||3|lilamon|02|||||false`,
`Sunmon|sunmon|2|Lesser|2|||1|coronamon||||03|02|false`,
`SuperStarmon|superstarmon|5|Mutant|5|||3|justimon|01|||||false`,
`Susanoomon|susanoomon|7|Wizard|8||TRUE|1||07|||||false`,
`Swanmon|swanmon|4|Bird|9|Love||4||08|||||false`,
`Swimmon|swimmon|3||3|||1|tylomon|||03|03|21|false`,
`Syakomon|syakomon|3|Crustacean|3|||2|octomon,gesomon,seadramon|01|||||false`,
`Tanemon|tanemon|2|Bulb|2|||4|palmon,floramon|01|||||false`,
`Tankmon|tankmon|4|Cyborg|4|||3|knightmon|01|||||false`,
`Tankmon|tankmon_light_green|4|Cyborg|4|||3||01||03|||false`,
`Tankmon|tankmon_orange|4|Cyborg|4|||3||01||03|||false`,
`Taomon|taomon|5|Wizard|5|||3|sakuyamon,sakuyamon_maid_mode,kuzuhamon,kuzuhamon_maid_mode|01|||||false`,
`Taomon|taomon_silver|5|Wizard|5|||1||01||03|||false`,
`Tapirmon|tapirmon|3|Holy Beast|3|||1|monochromon|01|||||false`,
`Tekkamon|tekkamon|5|Machine|5|||2||01|||||false`,
`Tentomon|tentomon|3|Insectoid|3|||1|kabuterimon,salamandermon,flamewizardmon|01|||||false`,
`Terriermon|terriermon|3|Beast|3|||1|gargomon,magnamon,rapidmon_gold|01|||||false`,
`Terriermon|terriermon_grey|3|Beast|3|||1||01||03|||false`,
`Terriermon|terriermon_purple|3|Beast|3|||1||01||03|||false`,
`Terriermon Assistant|terriermon_assistant|3|Beast|3|||1||01|03||||false`,
`Thunderbirdmon|thunderbirdmon|4|Giant Bird|9|Friendship||3||02|||||false`,
`Thundermon|thundermon|4|Mutant|4|||3|mamemon|01|||||false`,
`Titamon|titamon|6|Shaman|6|||2||13|||||false`,
`Tobiumon|tobiumon|4|Sea Animal|4|||1||13|||||false`,
`TobuCatmon|tobucatmon|4|Puppet/X-Antibody|4|||3||13|||||false`,
`Togemogumon|togemogumon|4|Mammal|9|Friendship||2||07|||||false`,
`Togemon|togemon|4|Vegetation|4|||3|lillymon,ponchomon|01|||||false`,
`Tokomon|tokomon|2|Lesser|2|||4|patamon,muchomon|01|||||false`,
`Tokomon|tokomon_blue|2|Lesser|2|||4||01||03|||false`,
`Tokomon|tokomon_yellow|2|Lesser|2|||4||01||03|||false`,
`TorikaraBallmon|torikaraballmon|2|Food|2|||3|burgermon|01|||||false`,
`Tortomon|tortomon|4|Reptile|4|||1||01|||||false`,
`Tortomon|tortomon_blue|4|Reptile|4|||1||01||03|||false`,
`Toucanmon|toucanmon|4|Bird|9|Kindness||4||02||03|||false`,
`ToyAgumon|toyagumon|3|Puppet|3|||1||01|||||false`,
`Triceramon|triceramon|5|Ceratopsian|5|||3|azulongmon|01|||||false`,
`Triceramon|triceramon_red|5|Ceratopsian|5|||3||01||03|||false`,
`Tsubumon|tsubumon|1|Slime|1|||4|upamon|01|||||false`,
`Tsukaimon|tsukaimon|3|Mammal|3|||2|devidramon,devimon,witchmon|01|||||false`,
`Tsumemon|tsumemon|2|Unidentified|2|||4|keramon,demidevimon|01|||||false`,
`Tsunomon|tsunomon|2|Lesser|2|||4|gabumon,elecmon,bearmon|01|||||false`,
`Turuiemon|turuiemon|4|Beastkin|4|||3|antylamon|01|||||false`,
`Tuskmon|tuskmon|4|Dinosaur|4|||2||01|||||false`,
`Tylomon|tylomon|4|Sea Animal|9|Sincerity||4|whamon|02|||||false`,
`Tyrannomon|tyrannomon|4|Dinosaur|4|||3|metaltyrannomon,mastertyrannomon,megadramon,skullgreymon|01|||||false`,
`TyrantKabuterimon|tyrantkabuterimon|6|Insectoid|6|||2||02|||||false`,
`UlforceVeedramon|ulforceveedramon|6|Holy Warrior/Royal Knight|6|||1|ulforceveedramon_future_mode|01|||||false`,
`UlforceVeedramon Future Mode|ulforceveedramon_future_mode|7|Holy Warrior|7|||1||01||03|||false`,
`UltimateBrachimon|ultimatebrachimon|6|Cyborg/X-Antibody|6|||3||13|||||false`,
`Unimon|unimon|4|Mythical Beast|4|||1|hippogriffomon|01|||||false`,
`Upamon|upamon|2|Amphibian|2|||4|armadillomon|01|||||false`,
`Vademon|vademon|5|Alien|5|||2|ebemon|01|||||false`,
`Vademon|vademon_red|5|Alien|5|||2||01||03|||false`,
`Vajramon|vajramon|5|Holy Beast/Deva|5|||2||08|||||false`,
`Valkyrimon|valkyrimon|6|Warrior|6|||4||01|||||false`,
`Varodurumon|varodurumon|6|Holy Bird|6|||1|chaosmon_valdur_arm|02|||||false`,
`Veedramon|veedramon|4|Mythical Dragon|4|||1|aeroveedramon|01|||||false`,
`Veedramon|veedramon_black|4|Mythical Dragon|4|||2||01|||||false`,
`Veemon|veemon|3|Mini Dragon|3|||4|exveemon,veedramon,flamedramon,raidramon,sethmon,yasyamon,honeybeemon,depthmon,sagittarimon,gargoylemon,kangarumon,magnamon,goldveedramon|01|||||false`,
`Veemon|veemon_red|3|Mini Dragon|3|||4||01||03|||false`,
`Veemon|veemon_green|3|Mini Dragon|3|||4||01||03|||false`,
`Vegiemon|vegiemon|4|Carnivorous Plant|4|||2|blossomon|01|||||false`,
`Vegiemon|vegiemon_green|4|Carnivorous Plant|4|||2||01||03|||false`,
`Velgemon|velgemon|4|Giant Bird|8|||6||07|||||false`,
`VenomMyotismon|venommyotismon|6|Dark Animal|6|||2|malomyotismon|01|||||false`,
`Venusmon|venusmon|6|Shaman/Olympos XII|6|||1||13|||||false`,
`Vermilimon|vermilimon|5|Ankylosaur|5|||3||01|||||false`,
`VictoryGreymon|victorygreymon|6|Dragonkin|6|||1|||||03|01|false`,
`Vikaralamon|vikaralamon|5|Holy Beast/Deva|5|||1||02|||||false`,
`Vikemon|vikemon|6|Beastkin|6|||4||01|||||false`,
`Vikemon|vikemon_blue|6|Beastkin|6|||4||01||03|||false`,
`Vikemon|vikemon_pink|6|Beastkin|6|||4||01||03|||false`,
`Vilemon|vilemon|4|Evil|4|||2||01|||||false`,
`Vilemon|vilemon_purple|4|Evil|4|||2||01||03|||false`,
`Viximon|viximon|2|Lesser|2|||4|renamon|01|||||false`,
`Volcanicdramon|volcanicdramon|6|Rock Dragon|6|||2||02|||||false`,
`Volcdramon|volcdramon|5|Dragon/X-Antibody|5|||3||13|||||false`,
`Vorvomon|vorvomon|3|Rock Dragon|3|||2|lavorvomon|02|||||false`,
`Vulcanusmon|vulcanusmon|6|Shaman/Olympos XII|6|||3||13|||||false`,
`Wanyamon|wanyamon|2|Lesser|2|||4|gaomon,bearmon|02|||||false`,
`WarGreymon|wargreymon|6|Dragonkin|6|||1|omnimon,omnimon_zwart|01|||||false`,
`WarGreymon|wargreymon_blue|6|Dragonkin|6|||1||01||03|||false`,
`WarGrowlmon|wargrowlmon|5|Cyborg|5|||2|gallantmon,megidramon,chaosgallantmon|01|||||false`,
`WarGrowlmon|wargrowlmon_yellow|5|Cyborg|5|||3||01|||||false`,
`WaruMonzaemon|warumonzaemon|5|Puppet|5|||2||01|||||false`,
`WaruSeadramon|waruseadramon|5|Sea Animal|5|||2||01|||||false`,
`WaruSeadramon|waruseadramon_shades|5|Sea Animal|5|||2||01||03|||false`,
`Weedmon|weedmon|4|Vegetation|4|||2||01|||||false`,
`Weedmon|weedmon_grey|4|Vegetation|4|||2||01||03|||false`,
`Wendigomon|wendigomon|4|Beast|4|||2|antylamon,antylamon_evil|01|||||false`,
`WereGarurumon|weregarurumon|5|Beastkin|5|||1|metalgarurumon,ancientgarurumon,cresgarurumon,zeedgarurumon|01|||||false`,
`WereGarurumon|weregarurumon_black|5|Beastkin|5|||2|metalgarurumon_black,bancholeomon,zeedgarurumon,cresgarurumon|01|||||false`,
`Whamon|whamon|4||4|||1|whamon_ultimate|01|||||false`,
`Whamon|whamon_ultimate|5||5|||1|neptunemon,marineangemon|01|02||||false`,
`Whamon|whamon_light_blue|4||4|||1||01||03|||false`,
`Whamon|whamon_white|4||4|||1||01||03|||false`,
`Wingdramon|wingdramon|5|Dragon|5|||1|slayerdramon|20||03|||false`,
`Wisemon|wisemon|5|Demon|5|||2|piedmon||||02|05|false`,
`Witchmon|witchmon|4|Demon|4|||3|bastemon|08|||||false`,
`Wizardmon|wizardmon|4|Wizard|4|||3|phantomon,mistymon,wisemon,skullmeramon,myotismon,flamewizardmon,ponchomon|01|||||false`,
`Woodmon|woodmon|4|Vegetation|4|||2|cherrymon|01|||||false`,
`Woodmon|woodmon_green|4|Vegetation|4|||2||01||03|||false`,
`Wormmon|wormmon|3|Larva|3|||4|stingmon,hudiemon,shadramon,flamewizardmon,togemogumon,aurumon,nohemon,searchmon,archelomon,bullmon,quetzalmon,bucchiemon,bucchiemon_green,kongoumon|01|||||false`,
`Wormmon|wormmon_red|3|Larva|3|||4||01||03|||false`,
`Wormmon|wormmon_blue|3|Larva|3|||4||01||03|||false`,
`Xiaomon|xiaomon|2|Lesser|2|||4|labramon|01||03|||false`,
`Xiaomon|xiaomon_brown|2|Lesser|2|||4||01||03|||false`,
`Yaamon|yaamon|2|Lesser|2|||4|impmon|01|||||false`,
`Yanmamon|yanmamon|4|Insectoid|4|||2||01|||||false`,
`Yanmamon|yanmamon_green|4|Insectoid|4|||2||01||03|||false`,
`Yasyamon|yasyamon|4|Puppet|9|Purity||1||02|||||true`,
`Yokomon|yokomon|2|Bulb|2|||4|biyomon|01|||||false`,
`Youkomon|youkomon|4|Mysterious Beast|4|||3|doumon|01|||||false`,
`Yuramon|yuramon|1|Seed|1|||4|tanemon,budmon|01|||||false`,
`Zanbamon|zanbamon|6|Wizard|6|||2||01|||||false`,
`ZeedGarurumon|zeedgarurumon|6|Cyborg|6|||3|||||03|01|false`,
`Zephyrmon|zephyrmon|4|Birdkin|8|||6|jetsilphymon|16|||||false`,
`Zephyrmon|zephyrmon_blue|4|Birdkin|8|||6||16||03|||false`,
`Zerimon|zerimon|1|Slime|1|||4|gummymon|01|||||false`,
`Zhuqiaomon|zhuqiaomon|6|Holy Beast/Sovereigns|6|||2|huanglongmon|15|||||false`,
`Zudomon|zudomon|5|Sea Beast|5|||1|plesiomon,vikemon|01|||||false`,
`Zurumon|zurumon|1|Slime|1|||4|pagumon|01|||||false`]